### ISSUE TITLE
Using `java_export` rule with Bazel 7.0.0 requires declaration of `@@bazel_tools//tools/jdk:toolchain_type'` toolchain

### ISSUE THREAD

**Issue by bmuschko** [bazelbuild/rules_jvm_external#1007]
Given the following code in a `BUILD` file.

```
load("@rules_jvm_external//:defs.bzl", "java_export")

java_export(
    name = "app-config-lib-export",
    maven_coordinates = "com.bmuschko.app:config:1.0.0",
    srcs = glob(["*.java"]),
    deps = [
        "@maven//:org_apache_commons_commons_configuration2"
    ],
    runtime_deps = [
        "@maven//:commons_beanutils_commons_beanutils"
    ]
)
```

Executing the command below produces an error message with Bazel 7.0.0.

```
$ bazelisk run --define "maven_repo=file://$HOME/.m2/repository" //src/main/java/com/bmuschko/app/config:app-config-lib-export
...
ERROR: /Users/bmuschko/dev/projects/getting-started-with-bazel/exercises/07-java-library-publish/solution/src/main/java/com/bmuschko/app/config/BUILD:14:12: in maven_project_jar rule //src/main/java/com/bmuschko/app/config:app-config-lib-export-project:
Traceback (most recent call last):
	File "/private/var/tmp/_bazel_bmuschko/ed0d727382899f7e5d5e87a7e60a8415/external/rules_jvm_external~4.5/private/rules/maven_project_jar.bzl", line 65, column 32, in _maven_project_jar_impl
		ijar = java_common.run_ijar(
	File "/virtual_builtins_bzl/common/java/java_common.bzl", line 92, column 68, in _run_ijar
Error in _check_java_toolchain_is_declared_on_rule: Rule 'maven_project_jar' in '/Users/bmuschko/dev/projects/getting-started-with-bazel/exercises/07-java-library-publish/solution/src/main/java/com/bmuschko/app/config/BUILD:14:12' must declare '@@bazel_tools//tools/jdk:toolchain_type' toolchain in order to use java_common. See https://github.com/bazelbuild/bazel/issues/18970.
```

**Comment by Mizux** [comment]
could be linked to https://github.com/bazelbuild/rules_jvm_external/commit/8391c5bcde3133a270837c1287b94240a5c71b34 ?

**Comment by c16a** [comment]
I think https://github.com/bazelbuild/rules_jvm_external/pull/1027 fixes this.
