### ISSUE TITLE
Transitive dep on egit is broken

### ISSUE THREAD

**Issue by parsnips** [bazelbuild/rules_jvm_external#1065]
During the coursier fetch, it could not find egit:

```
ERROR: An error occurred during the fetch of repository 'maven':
   Traceback (most recent call last):
	File "/mnt/data/root/.cache/bazel/_bazel_root/b7c0e49dc48477b0008fee9f624522db/external/rules_jvm_external/coursier.bzl", line 852, column 38, in _coursier_fetch_impl
		dep_tree = make_coursier_dep_tree(
	File "/mnt/data/root/.cache/bazel/_bazel_root/b7c0e49dc48477b0008fee9f624522db/external/rules_jvm_external/coursier.bzl", line 783, column 13, in make_coursier_dep_tree
		fail("Error while fetching artifact with coursier: " + exec_result.stderr)
Error in fail: Error while fetching artifact with coursier: Resolution error: Error downloading org.eclipse.mylyn.github:org.eclipse.egit.github.core:4.10.0.201712302008-r
  not found: https://maven.google.com/org/eclipse/mylyn/github/org.eclipse.egit.github.core/4.10.0.201712302008-r/org.eclipse.egit.github.core-4.10.0.201712302008-r.pom
  not found: https://repo1.maven.org/maven2/org/eclipse/mylyn/github/org.eclipse.egit.github.core/4.10.0.201712302008-r/org.eclipse.egit.github.core-4.10.0.201712302008-r.pom
  not found: https://s3-us-west-2.amazonaws.com/dynamodb-local/release/org/eclipse/mylyn/github/org.eclipse.egit.github.core/4.10.0.201712302008-r/org.eclipse.egit.github.core-4.10.0.201712302008-r.pom
  forbidden: https://repo.eclipse.org/content/groups/releases/org/eclipse/mylyn/github/org.eclipse.egit.github.core/4.10.0.201712302008-r/org.eclipse.egit.github.core-4.10.0.201712302008-r.pom
  ```
  
  It appears that [egit has actually moved](https://github.com/eclipse-egit/egit/issues/20)?  Don't know if this belongs here for you to change this dep, updgrade to unaffected coursier or fix upstream in coursier?

**Comment by parsnips** [comment]
This looks like one of our deps. Apologies.
