### ISSUE TITLE
[Bazel CI] main_activity_test failed at Bazel@HEAD


### ISSUE THREAD

**Issue by sgowroji** [bazelbuild/rules_jvm_external#1067]
CI: https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/3701#018e16aa-e31e-4be3-9eec-9bc3322a6c15

 Platform: MacOS

 Logs: 
```
FAIL: [0m//src/test:main_activity_test (Exit 1) (see /private/var/tmp/_bazel_buildkite/7bf723b7ae137136209a78bafdedea4d/execroot/_main/bazel-out/darwin_x86_64-fastbuild/testlogs/src/test/main_activity_test/test_attempts/attempt_1.log)
FAIL: [0m//src/test:main_activity_test (Exit 1) (see /private/var/tmp/_bazel_buildkite/7bf723b7ae137136209a78bafdedea4d/execroot/_main/bazel-out/darwin_x86_64-fastbuild/testlogs/src/test/main_activity_test/test_attempts/attempt_2.log)
FAIL: [0m//src/test:main_activity_test (Exit 1) (see /private/var/tmp/_bazel_buildkite/7bf723b7ae137136209a78bafdedea4d/execroot/_main/bazel-out/darwin_x86_64-fastbuild/testlogs/src/test/main_activity_test/test.log)
FAILED: [0m//src/test:main_activity_test (Summary)
Error: The command exited with status 1[0m
error: exit status 1
``` 
 Culprit: 

 Steps:
  ``` 
 git clone https://github.com/bazelbuild/rules_jvm_external
git reset 7ba59df6afa05c9e2d9356e1adb99f016a7c01eb  --hard
export USE_BAZEL_VERSION=ee8e833bbb530e4a84e3b9c2f4a07b48c78fad85
bazel test --flaky_test_attempts=3 --build_tests_only --local_test_jobs=18 --show_progress_rate_limit=5  //... 
 ``` 
 CC Greenteam @comius

**Comment by sgowroji** [comment]
[https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/3720#018e4049-edb6-443c-94f7-7287985a903a](https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/3720#018e4049-edb6-443c-94f7-7287985a903a)

Platform : Windows

```

ERROR: An error occurred during the fetch of repository '_main~maven~version_interval_testing':
   Traceback (most recent call last):
	File "C:/b/bk-windows-c78f/bazel-org-repo-root/rules_jvm_external/coursier.bzl", line 911, column 28, in _coursier_fetch_impl
		repository_ctx.download(coursier_download_urls, "coursier", sha256 = COURSIER_CLI_SHA256, executable = True)
Error in download: java.io.IOException: C:/b/cache/repos/v1/content_addressable/sha256/2b78bfdd3ef13fd1f42f158de0f029d7cbb1f4f652d51773445cf2b6f7918a87/file (Permission denied)
(04:07:05) ERROR: <builtin>: fetching coursier_fetch rule //:_main~maven~version_interval_testing: Traceback (most recent call last):
	File "C:/b/bk-windows-c78f/bazel-org-repo-root/rules_jvm_external/coursier.bzl", line 911, column 28, in _coursier_fetch_impl
		repository_ctx.download(coursier_download_urls, "coursier", sha256 = COURSIER_CLI_SHA256, executable = True)
Error in download: java.io.IOException: C:/b/cache/repos/v1/content_addressable/sha256/2b78bfdd3ef13fd1f42f158de0f029d7cbb1f4f652d51773445cf2b6f7918a87/file (Permission denied)
(04:07:06) ERROR: C:/b/bk-windows-c78f/bazel-org-repo-root/rules_jvm_external/tests/integration/BUILD:49:9: in genquery rule //tests/integration:version_interval_deps: errors were encountered while computing transitive closure of the scope: no such package '@@_main~maven~version_interval_testing//': java.io.IOException: C:/b/cache/repos/v1/content_addressable/sha256/2b78bfdd3ef13fd1f42f158de0f029d7cbb1f4f652d51773445cf2b6f7918a87/file (Permission denied)
(04:07:06) ERROR: C:/b/bk-windows-c78f/bazel-org-repo-root/rules_jvm_external/tests/integration/BUILD:49:9: Analysis of target '//tests/integration:version_interval_deps' failed
(04:07:06) ERROR: Analysis of target '//tests/integration:version_interval_deps_test' failed; build aborted: Analysis failed
(04:07:06) INFO: Elapsed time: 8.361s, Critical Path: 0.09s
(04:07:06) INFO: 1 process: 1 internal.
(04:07:06) ERROR: Build did NOT complete successfully
(04:07:06) ERROR: No test targets were found, yet testing was requested
(04:07:06) FAILED:
```

**Comment by sgowroji** [comment]
CC  @jin @[shs96c](https://github.com/shs96c) Can you take a look on the above failures. Thanks!

**Comment by jin** [comment]
#1073 to fix the `main_activity_test` failure. The Windows failure looks like a flake, and the retry succeeded.

**Comment by jin** [comment]
This is still not fixed, the tests are now failing with:

```
exec ${PAGER:-/usr/bin/less} "$0" || exit 1
Executing tests from //src/test:main_activity_test
-----------------------------------------------------------------------------
Error occurred during initialization of VM
java.lang.Error: Could not create SecurityManager
	at java.lang.System.initPhase3(java.base@11.0.19/System.java:2065)
Caused by: java.lang.ClassNotFoundException: allow
	at jdk.internal.loader.BuiltinClassLoader.loadClass(java.base@11.0.19/BuiltinClassLoader.java:581)
	at jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(java.base@11.0.19/ClassLoaders.java:178)
	at java.lang.ClassLoader.loadClass(java.base@11.0.19/ClassLoader.java:522)
	at java.lang.Class.forName0(java.base@11.0.19/Native Method)
	at java.lang.Class.forName(java.base@11.0.19/Class.java:398)
	at java.lang.System.initPhase3(java.base@11.0.19/System.java:2050)
```

**Comment by shs96c** [comment]
This is the reason `contrib_rules_jvm` has [this nasty hack](https://github.com/bazel-contrib/rules_jvm/blob/main/java/src/com/github/bazel_contrib/contrib_rules_jvm/junit5/allow.java).

**Comment by sgowroji** [comment]
CI is passing now and shows Green. We can close this issue.
