### ISSUE TITLE
Documented (and test) minimum supported host Java version

### ISSUE THREAD

**Issue by illicitonion** [bazelbuild/rules_jvm_external#1124]
I just tried to use rules_jvm_external on GitHub Actions using `windows-latest` which looks like it has Java 8 installed. I got errors like:

```
Repository rule coursier_fetch defined at:
  C:/users/runneradmin/_bazel_runneradmin/ddoqewg5/external/rules_jvm_external~6.0/coursier.bzl:1321:33: in <toplevel>
ERROR: An error occurred during the fetch of repository 'rules_jvm_external~6.0~maven~contrib_rules_jvm_tests':
   Traceback (most recent call last):
	File "C:/users/runneradmin/_bazel_runneradmin/ddoqewg5/external/rules_jvm_external~6.0/coursier.bzl", line 1066, column 43, in _coursier_fetch_impl
		hasher_stdout = _execute_with_argsfile(
	File "C:/users/runneradmin/_bazel_runneradmin/ddoqewg5/external/rules_jvm_external~6.0/coursier.bzl", line 182, column 13, in _execute_with_argsfile
		fail("Error while " + error_description + ": " + exec_result.stderr)
Error in fail: Error while obtaining the sha256 checksums: Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.UnsupportedClassVersionError: com/github/bazelbuild/rules_jvm_external/Hasher has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:[142](https://github.com/bazel-contrib/rules_jvm/actions/runs/8925430563/job/24514073647#step:6:143))
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:473)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:621)
```

This appears to be because of the Java version used to compile pre-compiled classes included in rules_jvm_external.

It would be great to document and test what the minimum supported _host_ JVM is, so that I can know what JVM I need installed on my CI workers, rather than guessing. (And I suspect if we don't have CI testing for this, folks will manually build these pre-built binaries on their machines with whatever JDK they happen to have set up, and this will regress in the future).

**Comment by shs96c** [comment]
The right thing for us to do is to use the hermetic java version somehow, rather than relying on whatever is installed on the system. We [recently removed the java version check](https://github.com/bazelbuild/rules_jvm_external/commit/4f56f7cec2fa3a47e34d48b8f6293785cfad7e3a) from the repo since it was relatively fragile.

In addition Java8 usage is dropping rapidly: any check we put in now will have minimal value, and the java error message is well-known by Java developers. I've updated the release page to indicate that Java 11 or above is required. Marking as closed.
