### ISSUE TITLE
Maven Resolver Fails with 'The entity "oslash" was referenced, but not declared' Error

### ISSUE THREAD

**Issue by tharakadesilva** [bazelbuild/rules_jvm_external#1144]
When using the new `maven` resolver, I am getting the following error:

```
The entity "oslash" was referenced, but not declared.
[ParallelDescriptorResolver-0-3] WARN org.eclipse.aether.internal.impl.DefaultRepositoryEventDispatcher - Failed to dispatch repository event to com.github.bazelbuild.rules_jvm_external.resolver.maven.CompoundListener
java.lang.RuntimeException: Unable to determine packaging
        at com.github.bazelbuild.rules_jvm_external.resolver.maven.CoordinateGatheringListener.artifactResolved(CoordinateGatheringListener.java:98)
        at com.github.bazelbuild.rules_jvm_external.resolver.maven.CompoundListener.lambda$artifactResolved$3(CompoundListener.java:46)
        at java.base/java.lang.Iterable.forEach(Iterable.java:75)
        at com.github.bazelbuild.rules_jvm_external.resolver.maven.CompoundListener.artifactResolved(CompoundListener.java:46)
        at org.eclipse.aether.internal.impl.DefaultRepositoryEventDispatcher.dispatch(DefaultRepositoryEventDispatcher.java:120)
        at org.eclipse.aether.internal.impl.DefaultRepositoryEventDispatcher.dispatch(DefaultRepositoryEventDispatcher.java:88)
        at org.eclipse.aether.internal.impl.DefaultArtifactResolver.artifactResolved(DefaultArtifactResolver.java:669)
        at org.eclipse.aether.internal.impl.DefaultArtifactResolver.evaluateDownloads(DefaultArtifactResolver.java:641)
        at org.eclipse.aether.internal.impl.DefaultArtifactResolver.performDownloads(DefaultArtifactResolver.java:545)
        at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:449)
        at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifacts(DefaultArtifactResolver.java:261)
        at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifact(DefaultArtifactResolver.java:243)
        at org.apache.maven.repository.internal.DefaultModelResolver.resolveModel(DefaultModelResolver.java:158)
        at org.apache.maven.repository.internal.DefaultModelResolver.resolveModel(DefaultModelResolver.java:204)
        at org.apache.maven.model.building.DefaultModelBuilder.readParentExternally(DefaultModelBuilder.java:1009)
        at org.apache.maven.model.building.DefaultModelBuilder.readParent(DefaultModelBuilder.java:801)
        at org.apache.maven.model.building.DefaultModelBuilder.build(DefaultModelBuilder.java:327)
        at org.apache.maven.model.building.DefaultModelBuilder.build(DefaultModelBuilder.java:243)
        at org.apache.maven.repository.internal.DefaultArtifactDescriptorReader.loadPom(DefaultArtifactDescriptorReader.java:284)
        at org.apache.maven.repository.internal.DefaultArtifactDescriptorReader.readArtifactDescriptor(DefaultArtifactDescriptorReader.java:175)
        at org.eclipse.aether.internal.impl.collect.bf.BfDependencyCollector.resolveCachedArtifactDescriptor(BfDependencyCollector.java:464)
        at org.eclipse.aether.internal.impl.collect.bf.BfDependencyCollector.resolveDescriptorForVersion(BfDependencyCollector.java:450)
        at org.eclipse.aether.internal.impl.collect.bf.BfDependencyCollector.lambda$resolveArtifactDescriptorAsync$1(BfDependencyCollector.java:417)
        at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
        at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762)
        at org.eclipse.aether.internal.impl.collect.bf.BfDependencyCollector.lambda$resolveArtifactDescriptorAsync$4(BfDependencyCollector.java:416)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: org.xml.sax.SAXParseException; systemId: file:/var/folders/bx/4rzt0r395ms8gx4z0htxt00w0000gn/T/resolver-home190040208606357561/.m2/repository/org/codehaus/plexus/ple
```

This is the associated POM file: [plexus-1.0.4.pom.zip](https://github.com/bazelbuild/rules_jvm_external/files/15413516/plexus-1.0.4.pom.zip).

## Additional Information
Bazel Version: 6.5.0
rules_jvm_eternal Version: 6.1
Operating System: MacOS

**Comment by shs96c** [comment]
What coordinates were you attempting to resolve? How would I replicate this locally?

**Comment by tharakadesilva** [comment]
Sorry @shs96c, the artifact is `org.codehaus.plexus:plexus:1.0.4`.

**Comment by cheister** [comment]
https://github.com/bazelbuild/rules_jvm_external/pull/1156 should fix this
