### ISSUE TITLE
Support "orbit" package types

### ISSUE THREAD

**Issue by mandrean** [bazelbuild/rules_jvm_external#116]
When using `rules_jvm_external` on a project pulling in an old version of Dropwizard (`"io.dropwizard:dropwizard-core:0.7.1",`), Bazel fails miserably because one of Dropwizard's declared dependencies in the POM being of package type `orbit`:

>**org.eclipse.jetty.orbit:javax.servlet:3.0.0.v201112011016**
>
```
<groupId>org.eclipse.jetty.orbit</groupId>
<artifactId>javax.servlet</artifactId>
<version>3.0.0.v201112011016</version>
<name>Jetty Orbit :: Servlet API</name>
<description>
This artifact originates from the Orbit Project at Eclipse, it is an osgi bundle and is signed as well.
</description>
<packaging>orbit</packaging>
```

Fetching/resolving it with the `coursier` CLI works fine though. Should be an easy fix.

**Comment by mandrean** [comment]
PR: https://github.com/bazelbuild/rules_jvm_external/pull/117

**Comment by jin** [comment]
Interesting - the error message for this gets printed **17** times.

```
Parsed artifact data: {"coord": "org.eclipse.jetty.orbit:javax.servlet:3.0.0.v201112011016", "file": None, "dependencies": []} and referenced by '//java/com/google/android/apps/authenticator:authenticator_lib'
ERROR: Analysis of target '//java/com/google/android/apps/authenticator:authenticator' failed; build aborted: no such package '@maven//': Traceback (most recent call last):
	File "/private/var/tmp/_bazel_jin/01df7c89101fa69de4358628ee7e3155/external/rules_jvm_external/coursier.bzl", line 536
		generate_imports(repository_ctx = repository_ctx, d..., <2 more arguments>)
	File "/private/var/tmp/_bazel_jin/01df7c89101fa69de4358628ee7e3155/external/rules_jvm_external/coursier.bzl", line 335, in generate_imports
		fail(error_message)

The artifact for org.eclipse.jetty.orbit:javax.servlet:3.0.0.v201112011016 was not downloaded. Perhaps its packaging type is
not one of: jar,aar,bundle,eclipse-plugin?

It is also possible that the packaging type of org.eclipse.jetty.orbit:javax.servlet:3.0.0.v201112011016 is specified
incorrectly in the POM file of an artifact that depends on it. For example,
org.eclipse.jetty.orbit:javax.servlet:3.0.0.v201112011016 may be an AAR, but the dependent's POM file specified its `<type>`
value to be a JAR.

The artifact(s) depending on org.eclipse.jetty.orbit:javax.servlet:3.0.0.v201112011016 are:



and their POM files are located at:



---
```
