### ISSUE TITLE
rules_jvm_external 6.3 breaks on some weird PackageInfo thing

### ISSUE THREAD

**Issue by dhalperi** [bazelbuild/rules_jvm_external#1244]
```
% bazel build //...
INFO: Invocation ID: 6ed468d3-897a-4183-b5f9-f9149fcbf453
ERROR: /private/var/tmp/_bazel_dhalperi/867aab6d821eccd913b791b64371139a/external/maven/BUILD:2604:11: in jvm_import rule @@maven//:org_apache_httpcomponents_core5_httpcore5: 
Traceback (most recent call last):
	File "/private/var/tmp/_bazel_dhalperi/867aab6d821eccd913b791b64371139a/external/rules_jvm_external/private/rules/jvm_import.bzl", line 76, column 24, in _jvm_import_impl
		PackageInfo(
	File "/private/var/tmp/_bazel_dhalperi/867aab6d821eccd913b791b64371139a/external/rules_license/rules/providers.bzl", line 50, column 23, in PackageInfo
		PackageInfo = provider(
Error: got unexpected field 'purl' in call to instantiate provider PackageInfo
ERROR: /private/var/tmp/_bazel_dhalperi/867aab6d821eccd913b791b64371139a/external/maven/BUILD:2604:11: Analysis of target '@@maven//:org_apache_httpcomponents_core5_httpcore5' failed
```

You can try it for yourself: https://github.com/batfish/batfish and then apply  this diff:

```diff
diff --git a/WORKSPACE b/WORKSPACE
index 6f12335358..1060d7f777 100644
--- a/WORKSPACE
+++ b/WORKSPACE
@@ -22,9 +22,9 @@ bazel_skylib_workspace()
 # External Java dependencies (from Maven)                #
 ##########################################################
 
-RULES_JVM_EXTERNAL_TAG = "6.2"
+RULES_JVM_EXTERNAL_TAG = "6.3"
 
-RULES_JVM_EXTERNAL_SHA = "808cb5c30b5f70d12a2a745a29edc46728fd35fa195c1762a596b63ae9cebe05"
+RULES_JVM_EXTERNAL_SHA = "c18a69d784bcd851be95897ca0eca0b57dc86bb02e62402f15736df44160eb02"
 
 http_archive(
     name = "rules_jvm_external",
```

**Comment by shs96c** [comment]
We have [`rules_license` as a dependency](https://github.com/bazelbuild/rules_jvm_external/blob/master/repositories.bzl#L50-L58), and from a glance at your `WORKSPACE` it should be loaded properly.

**Comment by shs96c** [comment]
So this is a classic problem of dependency ordering in your `WORKSPACE` file. If you load `rules_jvm_external` before `skylib`, you'll be fine.

**Comment by dhalperi** [comment]
We should probably just manage up `rules_license`, is that right?

**Comment by dhalperi** [comment]
I believe we had skylib first at some point because jvm_external brings in an older one otherwise.
