### ISSUE TITLE
Android: Desugaring fails on Sceneform with "Type com.google.ar.schemas.sceneform.LightingDef not present"

### ISSUE THREAD

**Issue by jfaust** [bazelbuild/rules_jvm_external#199]
### Description of the problem / feature request:

Trying to build an Android app using Sceneform, I get:
```
Exception in thread "main" java.lang.TypeNotPresentException: Type com.google.ar.schemas.sceneform.LightingDef not present
	at java.base/sun.invoke.util.BytecodeDescriptor.parseSig(BytecodeDescriptor.java:97)
	at java.base/sun.invoke.util.BytecodeDescriptor.parseMethod(BytecodeDescriptor.java:60)
	at java.base/sun.invoke.util.BytecodeDescriptor.parseMethod(BytecodeDescriptor.java:45)
	at java.base/java.lang.invoke.MethodType.fromDescriptor(MethodType.java:1134)
	at java.base/java.lang.invoke.MethodType.fromMethodDescriptorString(MethodType.java:1113)
	at com.google.devtools.build.android.desugar.LambdaDesugaring$InvokedynamicRewriter.toMethodHandle(LambdaDesugaring.java:660)
	at com.google.devtools.build.android.desugar.LambdaDesugaring$InvokedynamicRewriter.toJvmMetatype(LambdaDesugaring.java:647)
	at com.google.devtools.build.android.desugar.LambdaDesugaring$InvokedynamicRewriter.visitInvokeDynamicInsn(LambdaDesugaring.java:408)
	at org.objectweb.asm.ClassReader.readCode(ClassReader.java:2235)
	at org.objectweb.asm.ClassReader.readMethod(ClassReader.java:1275)
	at org.objectweb.asm.ClassReader.accept(ClassReader.java:679)
	at org.objectweb.asm.ClassReader.accept(ClassReader.java:391)
	at com.google.devtools.build.android.desugar.Desugar.desugarClassesInInput(Desugar.java:632)
	at com.google.devtools.build.android.desugar.Desugar.desugarOneInput(Desugar.java:463)
	at com.google.devtools.build.android.desugar.Desugar.desugar(Desugar.java:405)
	at com.google.devtools.build.android.desugar.Desugar.processRequest(Desugar.java:1035)
	at com.google.devtools.build.android.desugar.Desugar.main(Desugar.java:988)
Caused by: java.lang.ClassNotFoundException: Class com.google.ar.schemas.sceneform.LightingDef not found
	at com.google.devtools.build.android.desugar.io.HeaderClassLoader.findClass(HeaderClassLoader.java:53)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:588)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	at java.base/sun.invoke.util.BytecodeDescriptor.parseSig(BytecodeDescriptor.java:95)
	... 16 more
```

Disabling desugaring results in an opcode error I can't fix because `rules_jvm_external` doesn't allow me to specify `--android-sdk-min` to dex.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Use `rules_jvm_external` to bring in the sceneform library from maven:
```
RULES_JVM_EXTERNAL_TAG = "2.2"

RULES_JVM_EXTERNAL_SHA = "f1203ce04e232ab6fdd81897cf0ff76f2c04c0741424d192f28e65ae752ce2d6"

http_archive(
    name = "rules_jvm_external",
    sha256 = RULES_JVM_EXTERNAL_SHA,
    strip_prefix = "rules_jvm_external-%s" % RULES_JVM_EXTERNAL_TAG,
    url = "https://github.com/bazelbuild/rules_jvm_external/archive/%s.zip" % RULES_JVM_EXTERNAL_TAG,
)

load("@rules_jvm_external//:defs.bzl", "maven_install")

maven_install(
    artifacts = [
        "com.google.ar.sceneform.ux:sceneform-ux:aar:1.10.0",
    ],
    repositories = [
        "https://jcenter.bintray.com/",
        "https://maven.google.com",
        "https://repo1.maven.org/maven2",
    ],
)
```

Build an Android binary with `@maven//:com_google_ar_sceneform_ux_sceneform_ux` as a dependency.

### What operating system are you running Bazel on?

macOS 10.14.5

### What's the output of `bazel info release`?

release 0.27.1

###  Have you found anything relevant by searching the web?

Just this:
https://github.com/xamarin/XamarinComponents/issues/578

Which implies that Xamarin has this issue with VS2017, but not VS2019 - I believe in VS2019 they upgraded to use `d8` instead of `dx`

**Comment by jin** [comment]
Transferring this issue from the Bazel repo to rules_jvm_external, since it has nothing to do with the Android rules / desugaring.

**Comment by jfaust** [comment]
Thank you @jin!

**Comment by jin** [comment]
I can imagine `rules_jvm_external` providing a facility to address issues like this:

WORKSPACE:

```python
maven_install(
    artifacts = [
        "com.google.ar.sceneform.ux:sceneform-ux:aar:1.10.0",
    ],
    repositories = [
        "https://jcenter.bintray.com/",
        "https://maven.google.com",
        "https://repo1.maven.org/maven2",
    ],
    overwrite_target_labels = {
        "com.google.ar.sceneform:rendering": "//patches:sceneform_rendering",
    },
)
```

patches/BUILD:

```
aar_import(
    name = "sceneform_rendering",
    aar = "@maven//:v1/https/maven.google.com/com/google/ar/sceneform/rendering/1.10.0/rendering-1.10.0.aar",
    deps = [
        # Add the missing dependencies
        "@maven//:com_google_ar_core",
        "@maven//:com_google_ar_sceneform_sceneform_base",
        "@maven//:com_google_ar_sceneform_filament_android",
        ],
    tags = ["maven_coordinates=com.google.ar.sceneform:rendering:aar:1.10.0"],
)
```

Generated `maven_install` BUILD file:

```python
aar_import(
    name = "com_google_ar_sceneform_ux_sceneform_ux",
    tags = ["maven_coordinates=com.google.ar.sceneform.ux:sceneform-ux:1.10.0"],
    deps = [
        "@maven//:com_android_support_support_core_ui", 
        "@maven//:com_android_support_support_annotations", 
        "@maven//:com_android_support_support_fragment",
        "@maven//:android_arch_core_runtime",
        "@maven//:android_arch_lifecycle_viewmodel",
        "@maven//:android_arch_core_common",
        "@maven//:android_arch_lifecycle_runtime",
        "@maven//:com_google_ar_sceneform_filament_android",
        "@maven//:com_google_ar_sceneform_core", 
        "@maven//:com_android_support_support_core_utils",
        "@maven//:com_google_ar_core",
        "@maven//:android_arch_lifecycle_livedata_core", 
        "@maven//:com_android_support_support_compat", 
        "@maven//:com_google_ar_sceneform_sceneform_base", 
        "@maven//:android_arch_lifecycle_common",
        "//patches:sceneform_rendering", # instead of @maven//:com_google_ar_sceneform_rendering
      ],
    aar = "@maven//:v1/https/maven.google.com/com/google/ar/sceneform/ux/sceneform-ux/1.10.0/sceneform-ux-1.10.0.aar",
)
```

**Comment by geaden** [comment]
Hi, @jin!

I'm having the same issue with room dependencies in tests. It doesn't have dependency on `androidx_lifecycle_lifecycle_livedata_core`. So I followed instructions to declare a patch and referenced it in `override_targets`.

<details>
<summary>Patch</summary>
<p>

```
aar_import(
    name = "androidx_room_room_runtime",
    aar = "@android_app//:v1/https/maven.google.com/androidx/room/room-runtime/2.3.0/room-runtime-2.3.0.aar",
    tags = ["maven_coordinates=androidx.room:room-runtime:2.3.0"],
    visibility = [
        "//visibility:public",
    ],
    deps = [
        ":androidx_annotation_annotation_experimental",
        ":androidx_arch_core_core_runtime",
        ":androidx_lifecycle_lifecycle_livedata_core",
        ":androidx_room_room_common",
        ":androidx_sqlite_sqlite",
        ":androidx_sqlite_sqlite_framework",
    ],
)
```
</p>
</details>

However, `bazel build` now fails with:

```
ERROR: /path/to/workspace/src/third_party/room_runtime/BUILD.bazel:3:11: 
no such target '@android_app//:v1/https/maven.google.com/androidx/room/room-runtime/2.3.0/room-runtime-2.3.0.aar': 
target 'v1/https/maven.google.com/androidx/room/room-runtime/2.3.0/room-runtime-2.3.0.aar' not declared in package ''; 
however, a source file of this name exists.  
(Perhaps add 'exports_files(["v1/https/maven.google.com/androidx/room/room-runtime/2.3.0/room-runtime-2.3.0.aar"])' to /BUILD?) 
defined by /private/var/tmp/_bazel_app/c8cc6faf1db1751bb60bb524a772750d/external/android_app/BUILD and referenced by '//src/third_party/room_runtime:androidx_room_room_runtime'
```

Is it possible to overcome the error above?

**Comment by geaden** [comment]
> Hi, @jin!
> 
> I'm having the same issue with room dependencies in tests. It doesn't have dependency on `androidx_lifecycle_lifecycle_livedata_core`. So I followed instructions to declare a patch and referenced it in `override_targets`.
> 
> Patch
> However, `bazel build` now fails with:
> 
> ```
> ERROR: /path/to/workspace/src/third_party/room_runtime/BUILD.bazel:3:11: 
> no such target '@android_app//:v1/https/maven.google.com/androidx/room/room-runtime/2.3.0/room-runtime-2.3.0.aar': 
> target 'v1/https/maven.google.com/androidx/room/room-runtime/2.3.0/room-runtime-2.3.0.aar' not declared in package ''; 
> however, a source file of this name exists.  
> (Perhaps add 'exports_files(["v1/https/maven.google.com/androidx/room/room-runtime/2.3.0/room-runtime-2.3.0.aar"])' to /BUILD?) 
> defined by /private/var/tmp/_bazel_app/c8cc6faf1db1751bb60bb524a772750d/external/android_app/BUILD and referenced by '//src/third_party/room_runtime:androidx_room_room_runtime'
> ```
> 
> Is it possible to overcome the error above?

Ok, the issue was that I didn't configure artifacts pinning. After that the target is overriden.

**Comment by ahumesky** [comment]
Well in upgrading rules_jvm_external to work with the Starlark version of aar_import, aar_import checks if there are any missing classes, and apparently some code in `com.google.ar.sceneform:rendering:aar:1.10.0` depends on the class `com.google.ar.sceneform.assets.Loader` and I cannot for the life of me find an aar or other dependency with that class: https://maven.google.com/web/index.html?q=sceneform
