### ISSUE TITLE
repository_ctx has no method read

### ISSUE THREAD

**Issue by KaoruDev** [bazelbuild/rules_jvm_external#211]
Working with `scala_rules` and any version > 2.2. of `rules_jvm_external` I see this error:

```
ERROR: Analysis of target '//:vanilla-logger-grizzled' failed; build aborted: no such package '@maven//': Traceback (most recent call last):
	File "/private/var/tmp/_bazel_folder/91df1b4945922ef3942f4a4ed9bfa7dd/external/rules_jvm_external/coursier.bzl", line 727
		json_parse(repository_ctx.read(repository_c...")))
	File "/private/var/tmp/_bazel_folder/91df1b4945922ef3942f4a4ed9bfa7dd/external/rules_jvm_external/coursier.bzl", line 727, in json_parse
		repository_ctx.read(repository_ctx.path("dep-tree.js..."))
type 'repository_ctx' has no method read() and referenced by '//:vanilla-logger-grizzled'
```

WORKSPACE
```python
rules_scala_version="acac888c86e79110d1d08ab5578a7d0101c97963" # update this as needed

load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")
http_archive(
    name = "io_bazel_rules_scala",
    strip_prefix = "rules_scala-%s" % rules_scala_version,
    type = "zip",
    url = "https://github.com/bazelbuild/rules_scala/archive/%s.zip" % rules_scala_version,
)

load("@io_bazel_rules_scala//scala:toolchains.bzl", "scala_register_toolchains")
scala_register_toolchains()

load("@io_bazel_rules_scala//scala:scala.bzl", "scala_repositories")
scala_repositories()

protobuf_version="09745575a923640154bcf307fba8aedff47f240a"
protobuf_version_sha256="416212e14481cff8fd4849b1c1c1200a7f34808a54377e22d7447efdf54ad758"

http_archive(
    name = "com_google_protobuf",
    url = "https://github.com/protocolbuffers/protobuf/archive/%s.tar.gz" % protobuf_version,
    strip_prefix = "protobuf-%s" % protobuf_version,
    sha256 = protobuf_version_sha256,
)

# bazel-skylib 0.8.0 released 2019.03.20 (https://github.com/bazelbuild/bazel-skylib/releases/tag/0.8.0)
skylib_version = "0.8.0"
http_archive(
    name = "bazel_skylib",
    type = "tar.gz",
    url = "https://github.com/bazelbuild/bazel-skylib/releases/download/{}/bazel-skylib.{}.tar.gz".format (skylib_version, skylib_version),
    sha256 = "2ef429f5d7ce7111263289644d233707dba35e39696377ebab8b0bc701f7818e",
)

scala_repositories((
    "2.12.8",
    {
       "scala_compiler": "f34e9119f45abd41e85b9e121ba19dd9288b3b4af7f7047e86dc70236708d170",
       "scala_library": "321fb55685635c931eba4bc0d7668349da3f2c09aee2de93a70566066ff25c28",
       "scala_reflect": "4d6405395c4599ce04cea08ba082339e3e42135de9aae2923c9f5367e957315a"
    }
))

RULES_JVM_EXTERNAL_TAG = "2.5"
RULES_JVM_EXTERNAL_SHA = "249e8129914be6d987ca57754516be35a14ea866c616041ff0cd32ea94d2f3a1"

http_archive(
    name = "rules_jvm_external",
    strip_prefix = "rules_jvm_external-%s" % RULES_JVM_EXTERNAL_TAG,
    sha256 = RULES_JVM_EXTERNAL_SHA,
    url = "https://github.com/bazelbuild/rules_jvm_external/archive/%s.zip" % RULES_JVM_EXTERNAL_TAG,
)

load("@rules_jvm_external//:defs.bzl", "maven_install")

maven_install(
    name = "maven",
    artifacts = [
        "org.slf4j:slf4j-api:1.7.26",
        "org.clapper:grizzled-slf4j_2.12:1.3.4",
        "ch.qos.logback:logback-classic:1.2.3",
        "ch.qos.logback:logback-core:1.2.3",
        "org.scalatest:scalatest_2.12:3.0.5",
        "org.mockito:mockito-core:2.24.0"
    ],
    repositories = [
        "https://central.maven.org/maven2/",
        "https://jcenter.bintray.com/"
    ],
    fetch_sources = True,
)
```

BUILD
```python
load("@io_bazel_rules_scala//scala:scala.bzl", "scala_library", "scala_test")

scala_library(
    name = "vanilla-logger-grizzled",
    srcs = glob(["src/main/scala/com/tally/**/*.scala"]),
    deps = [
        "@maven//:org_clapper_grizzled_slf4j_2_12",
        "@maven//:org_slf4j_slf4j_api",
    ],
    visibility = ["//visibility:public"]
)

scala_test(
    name = "vanilla-logger-grizzled-test",
    srcs = glob(["src/test/scala/com/tally/**/*.scala"]),
    deps = [
        ":vanilla-logger-grizzled",
        "@maven//:org_slf4j_slf4j_api",
        "@maven//:org_clapper_grizzled_slf4j_2_12",
        "@maven//:org_scalatest_scalatest_2_12",
        "@maven//:org_mockito_mockito_core",
        "@maven//:ch_qos_logback_logback_classic",
        "@maven//:ch_qos_logback_logback_core"
    ]
)
```

Using `rules_jvm_external` 2.2 fixes the issue. I'm not familiar enough to determine whether this is a bug with `scala_rules` or with `rules_jvm_external`

**Comment by jin** [comment]
`repository_ctx.read` was added in Bazel 0.25. What's your Bazel version?

https://docs.bazel.build/versions/0.25.0/skylark/lib/repository_ctx.html#read

This should have been a major version bump for rules_jvm_external, sorry about that.

**Comment by KaoruDev** [comment]
ah that was it! I was on Bazel `0.24.1`, upgraded to `0.28.1` and it worked thanks!
