### ISSUE TITLE
Error compiling PNG with 2.10

### ISSUE THREAD

**Issue by BenHenning** [bazelbuild/rules_jvm_external#288]
Hi. I ran into an error when trying to use rules_jvm_external in a project that I'm migrating to Bazel. I was able to repro this issue with the Kotlin example app by changing its WORKSPACE to download rules_jvm_external instead of reference it locally:

```bazel
load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

android_sdk_repository(name = "androidsdk")

# BEGIN io_bazel_rules_kotlin

RULES_KOTLIN_VERSION = "9051eb053f9c958440603d557316a6e9fda14687"
RULES_JVM_EXTERNAL_VERSION = "2.10"

http_archive(
    name = "io_bazel_rules_kotlin",
    sha256 = "c36e71eec84c0e17dd098143a9d93d5720e81b4db32bceaf2daf939252352727",
    strip_prefix = "rules_kotlin-%s" % RULES_KOTLIN_VERSION,
    url = "https://github.com/bazelbuild/rules_kotlin/archive/%s.tar.gz" % RULES_KOTLIN_VERSION,
)

load("@io_bazel_rules_kotlin//kotlin:kotlin.bzl", "kotlin_repositories", "kt_register_toolchains")

kotlin_repositories()

kt_register_toolchains()

# END io_bazel_rules_kotlin

http_archive(
    name = "rules_jvm_external",
    strip_prefix = "rules_jvm_external-%s" % RULES_JVM_EXTERNAL_VERSION,
    sha256 = "1bbf2e48d07686707dd85357e9a94da775e1dbd7c464272b3664283c9c716d26",
    url = "https://github.com/bazelbuild/rules_jvm_external/archive/%s.zip" % RULES_JVM_EXTERNAL_VERSION,
)
load("@rules_jvm_external//:defs.bzl", "maven_install")

maven_install(
    artifacts = [
        "androidx.appcompat:appcompat:1.0.2",
        "androidx.core:core-ktx:1.0.1",
    ],
    repositories = [
        "https://maven.google.com",
        "https://repo1.maven.org/maven2",
    ],
)

```

When trying to build the android_kotlin_app I get the following error:

```
$ bazel build //:app
INFO: Writing tracer profile to 'C:/users/ben/_bazel_ben/54mmzc6h/command.profile.gz'
Loading:
Loading: 0 packages loaded
Analyzing: target //:app (0 packages loaded, 0 targets configured)
Analyzing: target //:app (3 packages loaded, 103 targets configured)
Analyzing: target //:app (3 packages loaded, 103 targets configured)
INFO: Analyzed target //:app (4 packages loaded, 247 targets configured).
INFO: Found 1 target...
[0 / 81] [Prepa] BazelWorkspaceStatusAction stable-status.txt
[441 / 464] Compiling Android resources for @maven//:androidx_appcompat_appcompat; 2s local
ERROR: C:/users/ben/_bazel_ben/54mmzc6h/external/maven/BUILD:19:1: Compiling Android resources for @maven//:androidx_appcompat_appcompat failed (Exit 1)
Nov 10, 2019 5:51:17 PM java.util.stream.ForEachOps$ForEachOp$OfRef accept
SEVERE: Error during Compiling bazel-out\android-armeabi-v7a-fastbuild\bin\external\maven\_aar\unzipped\resources\androidx_appcompat_appcompat\res\drawable-xxhdpi-v4\abc_btn_switch_to_on_mtrl_00001.9.png:
Command: external\androidsdk\build-tools\29.0.2\aapt2.exe\
        compile\
        -v\
        --legacy\
        -o\
        C:\Users\Ben\AppData\Local\Temp\android_resources_tmp1441246513683677242\compiled\bazel-out\android-armeabi-v7a-fastbuild\bin\external\maven\_aar\unzipped\resources\androidx_appcompat_appcompat\res\
        bazel-out\android-armeabi-v7a-fastbuild\bin\external\maven\_aar\unzipped\resources\androidx_appcompat_appcompat\res\drawable-xxhdpi-v4\abc_btn_switch_to_on_mtrl_00001.9.png
Output:
bazel-out\android-armeabi-v7a-fastbuild\bin\external\maven\_aar\unzipped\resources\androidx_appcompat_appcompat\res\drawable-xxhdpi-v4\abc_btn_switch_to_on_mtrl_00001.9.png: note: compiling PNG.

Nov 10, 2019 5:51:17 PM java.util.stream.ForEachOps$ForEachOp$OfRef accept
SEVERE: Error during Compiling bazel-out\android-armeabi-v7a-fastbuild\bin\external\maven\_aar\unzipped\resources\androidx_appcompat_appcompat\res\drawable-xxhdpi-v4\abc_menu_hardkey_panel_mtrl_mult.9.png:
Command: external\androidsdk\build-tools\29.0.2\aapt2.exe\
        compile\
        -v\
        --legacy\
        -o\
        C:\Users\Ben\AppData\Local\Temp\android_resources_tmp1441246513683677242\compiled\bazel-out\android-armeabi-v7a-fastbuild\bin\external\maven\_aar\unzipped\resources\androidx_appcompat_appcompat\res\
        bazel-out\android-armeabi-v7a-fastbuild\bin\external\maven\_aar\unzipped\resources\androidx_appcompat_appcompat\res\drawable-xxhdpi-v4\abc_menu_hardkey_panel_mtrl_mult.9.png
Output:
bazel-out\android-armeabi-v7a-fastbuild\bin\external\maven\_aar\unzipped\resources\androidx_appcompat_appcompat\res\drawable-xxhdpi-v4\abc_menu_hardkey_panel_mtrl_mult.9.png: note: compiling PNG.

Exception in thread "main" com.google.devtools.build.android.aapt2.ResourceCompiler$CompileError
        at com.google.devtools.build.android.aapt2.ResourceCompiler$CompileError.of(ResourceCompiler.java:110)
        at com.google.devtools.build.android.aapt2.ResourceCompiler$CompilingVisitor.getCompiledArtifacts(ResourceCompiler.java:422)
        at com.google.devtools.build.android.aapt2.ResourceCompiler.getCompiledArtifacts(ResourceCompiler.java:456)
        at com.google.devtools.build.android.UnvalidatedAndroidData.compile(UnvalidatedAndroidData.java:103)
        at com.google.devtools.build.android.CompileLibraryResourcesAction.main(CompileLibraryResourcesAction.java:140)
        at com.google.devtools.build.android.ResourceProcessorBusyBox$Tool$11.call(ResourceProcessorBusyBox.java:126)
        at com.google.devtools.build.android.ResourceProcessorBusyBox.processRequest(ResourceProcessorBusyBox.java:243)
        at com.google.devtools.build.android.ResourceProcessorBusyBox.main(ResourceProcessorBusyBox.java:204)
        Suppressed: java.lang.RuntimeException: Error during Compiling bazel-out\android-armeabi-v7a-fastbuild\bin\external\maven\_aar\unzipped\resources\androidx_appcompat_appcompat\res\drawable-xxhdpi-v4\abc_btn_switch_to_on_mtrl_00001.9.png:
Command: external\androidsdk\build-tools\29.0.2\aapt2.exe\
        compile\
        -v\
        --legacy\
        -o\
        C:\Users\Ben\AppData\Local\Temp\android_resources_tmp1441246513683677242\compiled\bazel-out\android-armeabi-v7a-fastbuild\bin\external\maven\_aar\unzipped\resources\androidx_appcompat_appcompat\res\
        bazel-out\android-armeabi-v7a-fastbuild\bin\external\maven\_aar\unzipped\resources\androidx_appcompat_appcompat\res\drawable-xxhdpi-v4\abc_btn_switch_to_on_mtrl_00001.9.png
Output:
bazel-out\android-armeabi-v7a-fastbuild\bin\external\maven\_aar\unzipped\resources\androidx_appcompat_appcompat\res\drawable-xxhdpi-v4\abc_btn_switch_to_on_mtrl_00001.9.png: note: compiling PNG.

                at com.google.devtools.build.android.CommandHelper.execute(CommandHelper.java:42)
                at com.google.devtools.build.android.AaptCommandBuilder.execute(AaptCommandBuilder.java:297)
                at com.google.devtools.build.android.aapt2.ResourceCompiler$CompileTask.compile(ResourceCompiler.java:226)
                at com.google.devtools.build.android.aapt2.ResourceCompiler$CompileTask.call(ResourceCompiler.java:173)
                at com.google.devtools.build.android.aapt2.ResourceCompiler$CompileTask.call(ResourceCompiler.java:120)
                at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:125)
                at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:57)
                at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:78)
                at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
                at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
                at java.base/java.lang.Thread.run(Thread.java:834)
        Suppressed: java.lang.RuntimeException: Error during Compiling bazel-out\android-armeabi-v7a-fastbuild\bin\external\maven\_aar\unzipped\resources\androidx_appcompat_appcompat\res\drawable-xxhdpi-v4\abc_menu_hardkey_panel_mtrl_mult.9.png:
Command: external\androidsdk\build-tools\29.0.2\aapt2.exe\
        compile\
        -v\
        --legacy\
        -o\
        C:\Users\Ben\AppData\Local\Temp\android_resources_tmp1441246513683677242\compiled\bazel-out\android-armeabi-v7a-fastbuild\bin\external\maven\_aar\unzipped\resources\androidx_appcompat_appcompat\res\
        bazel-out\android-armeabi-v7a-fastbuild\bin\external\maven\_aar\unzipped\resources\androidx_appcompat_appcompat\res\drawable-xxhdpi-v4\abc_menu_hardkey_panel_mtrl_mult.9.png
Output:
bazel-out\android-armeabi-v7a-fastbuild\bin\external\maven\_aar\unzipped\resources\androidx_appcompat_appcompat\res\drawable-xxhdpi-v4\abc_menu_hardkey_panel_mtrl_mult.9.png: note: compiling PNG.

                at com.google.devtools.build.android.CommandHelper.execute(CommandHelper.java:42)
                at com.google.devtools.build.android.AaptCommandBuilder.execute(AaptCommandBuilder.java:297)
                at com.google.devtools.build.android.aapt2.ResourceCompiler$CompileTask.compile(ResourceCompiler.java:226)
                at com.google.devtools.build.android.aapt2.ResourceCompiler$CompileTask.call(ResourceCompiler.java:173)
                at com.google.devtools.build.android.aapt2.ResourceCompiler$CompileTask.call(ResourceCompiler.java:120)
                at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:125)
                at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:57)
                at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:78)
                at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
                at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
                at java.base/java.lang.Thread.run(Thread.java:834)
Target //:app failed to build
```

Is this an issue with how I have the WORKSPACE configured, or a known issue? It doesn't repro on master when building with the relative repository reference rather than downloading 2.10.

**Comment by BenHenning** [comment]
Hmm this is starting to seem like a local issue, but I'm not sure from what. Using the local repository reference was working earlier, but now it's failing with the same error even after a bazel clean.

**Comment by jin** [comment]
What is the commit of your local `rules_jvm_external` HEAD?

**Comment by jin** [comment]
>  It doesn't repro on master when building with the relative repository reference rather than downloading 2.10.

Can you confirm that your local git master is the latest commit on this repo?

**Comment by BenHenning** [comment]
I can confirm that my local master branch is checked out and pointing to
07f28c. I had checked out a fresh repo right before the repro.

**Comment by jin** [comment]
This is most definitely a Windows path issue. Which Bazel version are you using?

**Comment by BenHenning** [comment]
I don’t have it in front of me at the moment, but I was using the latest
Bazel version as of last week.

**Comment by jigt-gft** [comment]
Hello @jin , I'm having the same problem:
```
$ bazel build //Common/Android/Apps/appAndroid1/src/main:bazel_app1
INFO: Analyzed target //Common/Android/Apps/appAndroid1/src/main:bazel_app1 (2 packages loaded, 346 targets configured).
INFO: Found 1 target...
ERROR: C:/users/yino/_bazel_yino/7ejrm6mn/external/maven/BUILD:315:1: Compiling Android resources for @maven//:androidx_core_core failed (Exit 1)
feb. 13, 2020 6:06:26 P. M. java.util.stream.ForEachOps$ForEachOp$OfRef accept
SEVERE: Error during Compiling bazel-out\android-armeabi-v7a-fastbuild\bin\external\maven\_aar\unzipped\resources\androidx_core_core\res\drawable-xhdpi-v4\notification_bg_low_normal.9.png:
Command: external\androidsdk\build-tools\29.0.2\aapt2.exe\
        compile\
        -v\
        --legacy\
        -o\
        C:\Users\YINO\AppData\Local\Temp\android_resources_tmp10610315464254463185\compiled\bazel-out\android-armeabi-v7a-fastbuild\bin\external\maven\_aar\unzipped\resources\androidx_core_core\res\
        bazel-out\android-armeabi-v7a-fastbuild\bin\external\maven\_aar\unzipped\resources\androidx_core_core\res\drawable-xhdpi-v4\notification_bg_low_normal.9.png
Output:
bazel-out\android-armeabi-v7a-fastbuild\bin\external\maven\_aar\unzipped\resources\androidx_core_core\res\drawable-xhdpi-v4\notification_bg_low_normal.9.png: note: compiling PNG.

Exception in thread "main" com.google.devtools.build.android.aapt2.ResourceCompiler$CompileError
        at com.google.devtools.build.android.aapt2.ResourceCompiler$CompileError.of(ResourceCompiler.java:112)
        at com.google.devtools.build.android.aapt2.ResourceCompiler$CompilingVisitor.getCompiledArtifacts(ResourceCompiler.java:472)
        at com.google.devtools.build.android.aapt2.ResourceCompiler.getCompiledArtifacts(ResourceCompiler.java:506)
        at com.google.devtools.build.android.UnvalidatedAndroidData.compile(UnvalidatedAndroidData.java:103)
        at com.google.devtools.build.android.CompileLibraryResourcesAction.main(CompileLibraryResourcesAction.java:140)
        at com.google.devtools.build.android.ResourceProcessorBusyBox$Tool$12.call(ResourceProcessorBusyBox.java:132)
        at com.google.devtools.build.android.ResourceProcessorBusyBox.processRequest(ResourceProcessorBusyBox.java:242)
        at com.google.devtools.build.android.ResourceProcessorBusyBox.main(ResourceProcessorBusyBox.java:203)
        Suppressed: java.lang.RuntimeException: Error during Compiling bazel-out\android-armeabi-v7a-fastbuild\bin\external\maven\_aar\unzipped\resources\androidx_core_core\res\drawable-xhdpi-v4\notification_bg_low_normal.9.png:
Command: external\androidsdk\build-tools\29.0.2\aapt2.exe\
        compile\
        -v\
        --legacy\
        -o\
        C:\Users\YINO\AppData\Local\Temp\android_resources_tmp10610315464254463185\compiled\bazel-out\android-armeabi-v7a-fastbuild\bin\external\maven\_aar\unzipped\resources\androidx_core_core\res\
        bazel-out\android-armeabi-v7a-fastbuild\bin\external\maven\_aar\unzipped\resources\androidx_core_core\res\drawable-xhdpi-v4\notification_bg_low_normal.9.png
Output:
bazel-out\android-armeabi-v7a-fastbuild\bin\external\maven\_aar\unzipped\resources\androidx_core_core\res\drawable-xhdpi-v4\notification_bg_low_normal.9.png: note: compiling PNG.

                at com.google.devtools.build.android.AaptCommandBuilder.execute(AaptCommandBuilder.java:318)
                at com.google.devtools.build.android.aapt2.ResourceCompiler$CompileTask.compile(ResourceCompiler.java:228)
                at com.google.devtools.build.android.aapt2.ResourceCompiler$CompileTask.call(ResourceCompiler.java:175)
                at com.google.devtools.build.android.aapt2.ResourceCompiler$CompileTask.call(ResourceCompiler.java:122)
                at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:125)
                at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:57)
                at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:78)
                at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
                at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
                at java.base/java.lang.Thread.run(Thread.java:834)
Target //Common/Android/Apps/appAndroid1/src/main:bazel_app1 failed to build
INFO: Elapsed time: 41.653s, Critical Path: 35.23s
INFO: 9 processes: 9 local.
FAILED: Build did NOT complete successfully
```
Do you know what I'm doing wrong? Have any tips about to solve this error?

Thank you for help

Regards

**Comment by jantoniucci** [comment]
+1

**Comment by jantoniucci** [comment]
Maybe this helps: the issue seems to be related on components that merges java & kotlin code. Corresponding rules are not managing well the resources.

**Comment by robinlinden** [comment]
I'm getting this same issue on https://github.com/robinlinden/aTox/commit/2b5b85fa898b797f5b46c31f74fc599760f0f527 on Windows.

**Comment by jin** [comment]
This is not an issue with rules_jvm_external, but with the Bazel Android rules on Windows. Closing.
