### ISSUE TITLE
MavenJarMigrator runs an invalid "buildozer -version" to check if it's installed

### ISSUE THREAD

**Issue by hex539** [bazelbuild/rules_jvm_external#342]
This should be "buildozer --version". At least with Buildozer 1.0, the single dash version will be rejected and the program will exit with a nonzero code:

```
buildozer -version
# Ensure build layout
No buildozer.spec found in the current directory. Abandon.
```
This leads to the migration script failing to detect buildozer and exiting with a misleading message:

```
Exception in thread "main" java.lang.AssertionError: buildozer is not found on your PATH. Download buildozer for your platform from https://github.com/bazelbuild/buildtools/releases and put the executable in your PATH.
	at rules.jvm.external.MavenJarMigrator.checkPrerequisites(MavenJarMigrator.java:45)
	at rules.jvm.external.MavenJarMigrator.main(MavenJarMigrator.java:33)
```

Running it with "--version" instead [here (L44)](https://github.com/bazelbuild/rules_jvm_external/blob/master/migration/java/rules/jvm/external/MavenJarMigrator.java#L44) fixes this.

**Comment by hex539** [comment]
This is user error from installing the first thing that came up for "buildozer", rather than the bazel build tools package of the same name.
