### ISSUE TITLE
//tests/integration:UnsafeSharedCacheTest failed to build on Ubuntu

### ISSUE THREAD

**Issue by meteorcloudy** [bazelbuild/rules_jvm_external#375]
Since https://buildkite.com/bazel/rules-jvm-external/builds/1199, this test is failing to build with the following error message:
```
Opening zip "external/unsafe_shared_cache/v1/https/repo1.maven.org/maven2/com/google/guava/guava/27.0-jre/guava-27.0-jre.jar": open(): No such file or directory
Unable to open Zip file external/unsafe_shared_cache/v1/https/repo1.maven.org/maven2/com/google/guava/guava/27.0-jre/guava-27.0-jre.jar: No such file or directory
```

I did some investigation and found that it will only fail to build when remote cache is enabled. 
Because it was green on the same commit before build 1199, the issue looks like caused by infra change. 

Another point worth notice is `external/unsafe_shared_cache/v1/https/repo1.maven.org/maven2/com/google/guava/guava/27.0-jre/guava-27.0-jre.jar` is a symlink pointing to another location. The file at the destination does exist.

/cc @jin @philwo

**Comment by meteorcloudy** [comment]
The symlink points to a file under `/tmp/custom_coursier_cache`, it looks like the sandbox prevent ijar from accessing that file?

**Comment by meteorcloudy** [comment]
@philwo The test failure of rules_jvm_external is failing due to this issue again.

**Comment by philwo** [comment]
The sandbox mounts a fresh, empty tmpfs on /tmp, which means that the /tmp from the host system is shadowed and files in there cannot be accessed. If this is what's happening (and it sounds like that's the problem here), then this is working as intended.

But the strange thing is, this has been the case on Bazel CI since it exists, so I wonder why it only now fails (and why it sometimes works!?).

**Comment by meteorcloudy** [comment]
I guess it happened to work for some reason and the result gets cached, so it keeps passing until the cache got cleaned or some Bazel change forced it to rerun.

**Comment by jin** [comment]
>  so I wonder why it only now fails (and why it sometimes works!?).

I added support for custom `COURSIER_CACHE` locations in https://github.com/bazelbuild/rules_jvm_external/commit/7badfbe1947ee53b393947251d1fcafdab714b60. 

If /tmp is used for tmpfs, is there an on-disk writable location I can use for the tests?

**Comment by philwo** [comment]
@jin On Bazel CI's Linux machines, you should be able to use e.g. `/var/lib/buildkite-agent/coursier_cache`. It's an implementation detail, but used in a few other places, so unlikely to change (and if, I can just fix the path here, too). 😊

**Comment by philwo** [comment]
Does the location have to be writable from inside the tests? If yes, you have to add `--sandbox_writable_path=/var/lib/buildkite-agent/coursier_cache` to the `test_flags` and ensure via an `mkdir` in the `shell_commands`  that the directory exists before Bazel starts.

**Comment by jin** [comment]
No it doesn't, it's accessed in a repository rule.

**Comment by jin** [comment]
That directory seems to be problematic on macOS:

```

ERROR: An error occurred during the fetch of repository 'duplicate_artifacts_test':
--
  | Error while fetching artifact with coursier: Exception in thread "main" java.nio.file.AccessDeniedException: /var/lib/buildkite-agent
  | at sun.nio.fs.UnixException.translateToIOException(UnixException.java:84)
  | at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
  | at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
  | at sun.nio.fs.UnixFileSystemProvider.createDirectory(UnixFileSystemProvider.java:384)
  | at java.nio.file.Files.createDirectory(Files.java:674)
  | at java.nio.file.Files.createAndCheckIsDirectory(Files.java:781)
  | at java.nio.file.Files.createDirectories(Files.java:767)
  | at coursier.paths.Util.createDirectories(Util.java:64)
  | at coursier.paths.CachePath.withStructureLock(CachePath.java:124)
  | at coursier.cache.CacheLocks$.withStructureLock(CacheLocks.scala:21)
  | at coursier.cache.CacheLocks$.withLockOr(CacheLocks.scala:38)
  | at coursier.cache.FileCache.$anonfun$download$32(FileCache.scala:506)
  | at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:659)
  | at scala.util.Success.$anonfun$map$1(Try.scala:255)
  | at scala.util.Success.map(Try.scala:213)
  | at scala.concurrent.Future.$anonfun$map$1(Future.scala:292)
  | at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:33)
  | at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33)
  | at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
  | at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
  | at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
  | at java.lang.Thread.run(Thread.java:748)
  | ERROR: Error while fetching artifact with coursier: Exception in thread "main" java.nio.file.AccessDeniedException: /var/lib/buildkite-agent
  | at sun.nio.fs.UnixException.translateToIOException(UnixException.java:84)
  | at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
  | at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
  | at sun.nio.fs.UnixFileSystemProvider.createDirectory(UnixFileSystemProvider.java:384)
  | at java.nio.file.Files.createDirectory(Files.java:674)
  | at java.nio.file.Files.createAndCheckIsDirectory(Files.java:781)
  | at java.nio.file.Files.createDirectories(Files.java:767)
  | at coursier.paths.Util.createDirectories(Util.java:64)
  | at coursier.paths.CachePath.withStructureLock(CachePath.java:124)
  | at coursier.cache.CacheLocks$.withStructureLock(CacheLocks.scala:21)
  | at coursier.cache.CacheLocks$.withLockOr(CacheLocks.scala:38)
  | at coursier.cache.FileCache.$anonfun$download$32(FileCache.scala:506)
  | at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:659)
  | at scala.util.Success.$anonfun$map$1(Try.scala:255)
  | at scala.util.Success.map(Try.scala:213)
  | at scala.concurrent.Future.$anonfun$map$1(Future.scala:292)
  | at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:33)
  | at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33)
  | at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
  | at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
  | at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
  | at java.lang.Thread.run(Thread.java:748)
  | INFO: Elapsed time: 1.799s
  | INFO: 0 processes.
  | FAILED: Build did NOT complete successfully (0 packages loaded)
  | FAILED: Build did NOT complete successfully (0 packages loaded)
  | mkdir: /var/lib/buildkite-agent/coursier_cache: Permission denied
  | Traceback (most recent call last):
  | File "bazelci.py", line 2926, in <module>
  | sys.exit(main())
  | File "bazelci.py", line 2906, in main
  | bazel_version=task_config.get("bazel") or configs.get("bazel"),
  | File "bazelci.py", line 850, in execute_commands
  | execute_shell_commands(task_config.get("shell_commands", None))
  | File "bazelci.py", line 1174, in execute_shell_commands
  | execute_command([shell_command], shell=True)
  | File "bazelci.py", line 1714, in execute_command
  | args, shell=shell, check=fail_if_nonzero, env=os.environ, cwd=cwd
  | File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 512, in run
  | output=stdout, stderr=stderr)
  | subprocess.CalledProcessError: Command '['bazel run @unpinned_regression_testing//:pin\nbazel run @unpinned_maven_install_in_custom_location//:pin\nbazel run @duplicate_artifacts_test//:pin\nmkdir -p $COURSIER_CACHE']' returned non-zero exit status 1.
``

**Comment by philwo** [comment]
Yes, that directory doesn't exist on macOS. The path varies per platform. On macOS you can use `/Users/buildkite/coursier_cache`.

**Comment by philwo** [comment]
Using `$HOME` (which resolves to `/var/lib/buildkite-agent` on Linux and `/Users/buildkite` on macOS) should also work, if you want to parametrize it. :)
