### ISSUE TITLE
ArrayIndexOutOfBoundsException when using java_export with jcenter

### ISSUE THREAD

**Issue by birdayz** [bazelbuild/rules_jvm_external#486]
Using version 3.3

```
java_export(
  name = "kafka-streams-contrib-publish",
  maven_coordinates = "de.nerden:kafka-streams-contrib:0.1.1",
  runtime_deps = [
    "//:kafka-streams-contrib",
  ],
)
```

The repo can be found here: https://github.com/birdayz/kafka-streams-contrib/blob/bazel/BUILD (branch bazel)

i'm calling:

```
bazel run --define "maven_repo=https://api.bintray.com/maven/birdayz/oss-releases/kafka-streams-contrib/;publish=1" --define "maven_user=birdayz" --define "maven_password=my-api-key" //:kafka-streams-contrib-publish.publish
```

Output:

```
Uploading de.nerden:kafka-streams-contrib:0.1.1 to https://api.bintray.com/maven/birdayz/oss-releases/kafka-streams-contrib/;publish=1
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: Index 2 out of bounds for length 1
	at rules.jvm.external.maven.MavenPublisher.main(MavenPublisher.java:60)
```

if i change the repo URL (maybe it's incorrect..) to `https://api.bintray.com/maven/birdayz/oss-releases`, i get:

```
Exception in thread "main" java.util.concurrent.ExecutionException: java.lang.RuntimeException: Basic realm="Bintray API Realm"
	at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:395)
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2022)
	at rules.jvm.external.maven.MavenPublisher.main(MavenPublisher.java:82)
Caused by: java.lang.RuntimeException: Basic realm="Bintray API Realm"
	at rules.jvm.external.maven.MavenPublisher.lambda$httpUpload$1(MavenPublisher.java:186)
	at rules.jvm.external.maven.MavenPublisher.lambda$upload$0(MavenPublisher.java:154)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```
Sadly, also not much more helpful.

it's hard to tell for me what the actual problem is, given the exception.. 

edit: it seems to be this line:
```
    Credentials credentials = new Credentials(args[2], args[3], Boolean.parseBoolean(args[1]));
```
apparently args[2] and [3] are not present. i followed the example though

edit2: i suspect that the ";" is the problem. if i remove it, i "just" get the auth error. seems i'm not getting the repo URL right.

**Comment by birdayz** [comment]
Okay..i found it out. It's the same error as in https://github.com/bazelbuild/rules_jvm_external/issues/476 . It's fixed in master.
