### ISSUE TITLE
Error in fail: Error while fetching artifact with coursier: Timed out

### ISSUE THREAD

**Issue by subotic** [bazelbuild/rules_jvm_external#487]
Since moving to macOS Big Sur, on some developer machines (two are working and two are not), we are encountering the attached problem. Since it works on some machines and not on others, I assume it is some local incompatibility. Maybe someone more knowledgeable about the inner workings of the rules, could point me in the right direction?

```
╭─ subotic@iml-stargazer  ~/_github.com/dasch-swiss/dsp-api   wip/DSP-1099-Update-Bazel-maven-rules ⍟7 
╰─ bazel fetch @maven//...
INFO: Repository maven instantiated at:
  /Users/subotic/_github.com/dasch-swiss/dsp-api/WORKSPACE:104:13: in <toplevel>
  /Users/subotic/_github.com/dasch-swiss/dsp-api/third_party/dependencies.bzl:16:18: in dependencies
  /private/var/tmp/_bazel_subotic/023af0d5fb0e1e4c98396d78cd4c3744/external/rules_jvm_external/defs.bzl:102:19: in maven_install
Repository rule coursier_fetch defined at:
  /private/var/tmp/_bazel_subotic/023af0d5fb0e1e4c98396d78cd4c3744/external/rules_jvm_external/coursier.bzl:950:33: in <toplevel>
INFO: Repository 'maven' used the following cache hits instead of downloading the corresponding file.
 * Hash '5c0a0a3ea600f302ee458b30317425dd9632d1ad8882259fcaf4e9b868b2b1ef' for https://github.com/stedolan/jq/releases/download/jq-1.6/jq-osx-amd64
 * Hash '6598d9277705ad8369a4f9c64217fbc31c19234f2cbcca9b1e5c4300a3abb317' for https://github.com/coursier/coursier/releases/download/v2.0.0-RC5-3/coursier.jar
 * Hash 'af986793a515d500ab2d35f8d2aecd656e764504b789b66d7e1a0b727a124c44' for https://github.com/stedolan/jq/releases/download/jq-1.6/jq-linux64
 * Hash 'a51d36968dcbdeabb3142c6f5cf9b401a65dc3a095f3144bd0c118d5bb192753' for https://github.com/stedolan/jq/releases/download/jq-1.6/jq-win64.exe
If the definition of 'maven' was updated, verify that the hashes were also updated.
ERROR: An error occurred during the fetch of repository 'maven':
   Traceback (most recent call last):
	File "/private/var/tmp/_bazel_subotic/023af0d5fb0e1e4c98396d78cd4c3744/external/rules_jvm_external/coursier.bzl", line 660, column 38, in _coursier_fetch_impl
		dep_tree = make_coursier_dep_tree(
	File "/private/var/tmp/_bazel_subotic/023af0d5fb0e1e4c98396d78cd4c3744/external/rules_jvm_external/coursier.bzl", line 601, column 13, in make_coursier_dep_tree
		fail("Error while fetching artifact with coursier: " + exec_result.stderr)
Error in fail: Error while fetching artifact with coursier: Timed out
ERROR: Error while fetching artifact with coursier: Timed out
Loading: 0 packages loaded
```

os: macOS Big Sur 11.0.1
cpu: Intel
bazel: 3.7.1 (and 3.7.0 before that)

Thanks,
Ivan

**Comment by cheister** [comment]
Can you run `RJE_VERBOSE=true bazel fetch @maven//...` and see if you get more information about what is timing out?  I assume you're also the latest version of rules_jvm_external?

**Comment by subotic** [comment]
Thank you very much for your help. The `RJE_VERBOSE=true` flag was very useful, in that it showed that it was always some other artifact. This made me widen the scope. As it turns out, our University issued Cisco VPN software installed some packet filters, which are automatically active with Big Sur and were messing with the network. Removing those fixed the issue.
