### ISSUE TITLE
rules_jvm_external broken on Bazel CI

### ISSUE THREAD

**Issue by c-parsons** [bazelbuild/rules_jvm_external#502]
rules_jvm_external has been broken on CI since Dec 17.

Example failure: https://buildkite.com/bazel/rules-jvm-external/builds/1774#62c74da4-24ec-4146-b192-4befe9430d61

```
ERROR: An error occurred during the fetch of repository 'unpinned_regression_testing':
--
  | Traceback (most recent call last):
  | File "/workdir/coursier.bzl", line 710, column 38, in _coursier_fetch_impl
  | dep_tree = make_coursier_dep_tree(
  | File "/workdir/coursier.bzl", line 649, column 13, in make_coursier_dep_tree
  | fail("Error while fetching artifact with coursier: " + exec_result.stderr)
  | Error in fail: Error while fetching artifact with coursier: Resolution error: Error downloading com.digitalasset:damlc:100.12.1
  | not found: https://repo1.maven.org/maven2/com/digitalasset/damlc/100.12.1/damlc-100.12.1.pom
  | not found: https://digitalassetsdk.bintray.com/DigitalAssetSDK/com/digitalasset/damlc/100.12.1/damlc-100.12.1.pom
  | not found: https://maven.google.com/com/digitalasset/damlc/100.12.1/damlc-100.12.1.pom
  | not found: https://packages.confluent.io/maven/com/digitalasset/damlc/100.12.1/damlc-100.12.1.pom
  | ERROR: Error while fetching artifact with coursier: Resolution error: Error downloading com.digitalasset:damlc:100.12.1
  | not found: https://repo1.maven.org/maven2/com/digitalasset/damlc/100.12.1/damlc-100.12.1.pom
  | not found: https://digitalassetsdk.bintray.com/DigitalAssetSDK/com/digitalasset/damlc/100.12.1/damlc-100.12.1.pom
  | not found: https://maven.google.com/com/digitalasset/damlc/100.12.1/damlc-100.12.1.pom
  | not found: https://packages.confluent.io/maven/com/digitalasset/damlc/100.12.1/damlc-100.12.1.pom
```

**Comment by jin** [comment]
#503
