### ISSUE TITLE
bazel run @maven//:outdated crashes with NPE (4.0, java11)

### ISSUE THREAD

**Issue by dhalperi** [bazelbuild/rules_jvm_external#507]
WORKSPACE:

```
load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

RULES_JVM_EXTERNAL_TAG = "4.0"

RULES_JVM_EXTERNAL_SHA = "31701ad93dbfe544d597dbe62c9a1fdd76d81d8a9150c2bf1ecf928ecdf97169"

http_archive(
    name = "rules_jvm_external",
    sha256 = RULES_JVM_EXTERNAL_SHA,
    strip_prefix = "rules_jvm_external-%s" % RULES_JVM_EXTERNAL_TAG,
    url = "https://github.com/bazelbuild/rules_jvm_external/archive/%s.zip" % RULES_JVM_EXTERNAL_TAG,
)

load("@rules_jvm_external//:defs.bzl", "maven_install")

maven_install(
    artifacts = [
        "javax.inject:javax.inject:1",
    ],
    repositories = [
        "https://repo1.maven.org/maven2",
    ],
)
```

java --version:

```
openjdk 11.0.8 2020-07-14
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.8+10)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.8+10, mixed mode)
```

os: `macOS Catalina 10.15.7 (19H114)`

bazel version:
```
Bazelisk version: 1.6.1
Build label: 3.7.2
Build target: bazel-out/darwin-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Thu Dec 17 17:02:20 2020 (1608224540)
Build timestamp: 1608224540
Build timestamp as int: 1608224540
```

Output:
```
bazel run @maven//:outdated
INFO: Invocation ID: 7b754f1a-1fa5-4587-9a43-59f1e871c245
INFO: Analyzed target @maven//:outdated (3 packages loaded, 5 targets configured).
INFO: Found 1 target...
Target @maven//:outdated up-to-date:
  bazel-bin/external/maven/outdated
INFO: Elapsed time: 0.330s, Critical Path: 0.01s
INFO: 1 process: 1 internal.
INFO: Build completed successfully, 1 total action
INFO: Build completed successfully, 1 total action
Checking for updates of 1 artifacts against the following repositories:
	https://repo1.maven.org/maven2

Exception in thread "main" java.lang.NullPointerException
	at rules.jvm.external.maven.Outdated.getReleaseVersion(Outdated.java:56)
	at rules.jvm.external.maven.Outdated.main(Outdated.java:112)
```

**Comment by dhalperi** [comment]
I suspect this is related to there only have ever been 1 released version.

https://repo1.maven.org/maven2/javax/inject/javax.inject/maven-metadata.xml

```xml
<metadata>
 <groupId>javax.inject</groupId>
 <artifactId>javax.inject</artifactId>
 <version>1</version>
 <versioning>
  <versions>
   <version>1</version>
  </versions>
  <lastUpdated>20100720032040</lastUpdated>
 </versioning>
</metadata>
```

**Comment by dhalperi** [comment]
A random, fresh, common (jackson-core) metadata file doesn't even have a top-level `<version>` tag: https://repo1.maven.org/maven2/com/fasterxml/jackson/core/jackson-core/maven-metadata.xml

**Comment by dhalperi** [comment]
Tried a local fix, but having a hard time figuring out how to get it to use HEAD outdated instead of the deploy jar. Are there instructions somewhere?

**Comment by jin** [comment]
cc @cheister
