### ISSUE TITLE
rules_jvm_external CI failing with Bazel@HEAD

### ISSUE THREAD

**Issue by c-parsons** [bazelbuild/rules_jvm_external#536]
rules_jvm_external CI failing with Bazel@HEAD as of our CI run on yesterday, Sun, Mar 14.

Example failure:
https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/1954#ee6bc81f-60ea-4720-8e2e-5c0444f885be

Log snippet:
```
1) initializationError(com.google.android.apps.common.testing.suite.AndroidDeviceTestSuite)
java.lang.IllegalStateException: Bad exit code: 1. Command: [/b/f/w/__main__/bazel-out/k8-fastbuild/bin/src/test/greeter_test.runfiles/__main__/../android_test_support/tools/android/emulated_devices/generic_phone/android_23_x86_qemu2, --action=start, --adb_server_port=33345, --adb_port=36971, --emulator_port=43394, --logcat_path=/b/f/w/__main__/bazel-out/k8-fastbuild/testlogs/src/test/greeter_test/test.outputs/device_logcat/logcat5686736159254600160.txt, --apks=/b/f/w/__main__/bazel-out/k8-fastbuild/bin/src/test/greeter_test.runfiles/__main__/src/main/greeter_app.apk /b/f/w/__main__/bazel-out/k8-fastbuild/bin/src/test/greeter_test.runfiles/__main__/src/test/greeter_test_app.apk /b/f/w/__main__/_tmp/460ffc733e95b13fc1eca23e7ea87627/1415739490932233877/services/test_services.apk /b/f/w/__main__/_tmp/460ffc733e95b13fc1eca23e7ea87627/1415739490932233877/runner/android_test_orchestrator/stubapp/stubapp.apk, --system_apks=, --subprocess_log_dir=/b/f/w/__main__/bazel-out/k8-fastbuild/testlogs/src/test/greeter_test/test.outputs/broker_logs/exec-1, --nolaunch_in_seperate_session, --start_vnc_on_port=0, --initial_locale=en-US, --initial_ime=com.android.inputmethod.latin/.LatinIME, --kvm_device=/dev/kvm, --grant_runtime_permissions=true, --logcat_filter='*:I', --enable_display, --nopreverify_apks, --noenable_console_auth, --enable_gps, --export_launch_metadata_path=/b/f/w/__main__/_tmp/460ffc733e95b13fc1eca23e7ea87627/emulator_meta9199270164088916249.pb, --net_type=fastnet, --long_press_timeout=5000].
=====Error begin:
...
Traceback (most recent call last):
File "/b/f/w/__main__/bazel-out/k8-fastbuild/bin/src/test/greeter_test.runfiles/android_test_support/tools/android/emulator/unified_launcher.py", line 1129, in <module>
app.run(main)
File "/b/f/w/__main__/bazel-out/k8-fastbuild/bin/src/test/greeter_test.runfiles/absl_py/absl/app.py", line 262, in run
_run_main(main, argv)
File "/b/f/w/__main__/bazel-out/k8-fastbuild/bin/src/test/greeter_test.runfiles/absl_py/absl/app.py", line 227, in _run_main
sys.exit(main(argv))
File "/b/f/w/__main__/bazel-out/k8-fastbuild/bin/src/test/greeter_test.runfiles/android_test_support/tools/android/emulator/unified_launcher.py", line 1099, in main
EntryPoint(reporter)
File "/b/f/w/__main__/bazel-out/k8-fastbuild/bin/src/test/greeter_test.runfiles/android_test_support/tools/android/emulator/unified_launcher.py", line 935, in EntryPoint
mini_boot, FLAGS.sim_access_rules_file, FLAGS.phone_number)
File "/b/f/w/__main__/bazel-out/k8-fastbuild/bin/src/test/greeter_test.runfiles/android_test_support/tools/android/emulator/unified_launcher.py", line 663, in _Run
snapshot_file=FLAGS.snapshot_file)
File "/b/f/w/__main__/bazel-out/k8-fastbuild/bin/src/test/greeter_test.runfiles/android_test_support/tools/android/emulator/unified_launcher.py", line 464, in _RestartDevice
'Try to run snapshot images with KVM support on non-KVM machine.')
AssertionError: Try to run snapshot images with KVM support on non-KVM machine.
=====Error end
```

Oddly, build is still passing using release Bazel. I wonder if this is a machine configuration issue?

I pinged @ahumesky for some preliminary guidance, and he guessed that it's possible that our runners may have changed recently (say, that they no longer have KVM enabled, which is a requirement for running emulator tests)

**Comment by jin** [comment]
This should require the same fix as https://github.com/android/testing-samples/pull/327

**Comment by jin** [comment]
https://github.com/bazelbuild/rules_jvm_external/pull/537
