### ISSUE TITLE
rules_jvm_external failing on Bazel CI

### ISSUE THREAD

**Issue by meteorcloudy** [bazelbuild/rules_jvm_external#551]
https://buildkite.com/bazel/rules-jvm-external/builds/2004
```
ERROR: An error occurred during the fetch of repository 'unpinned_regression_testing':
   Traceback (most recent call last):
	File "/Users/buildkite/builds/bk-imacpro-20/bazel/rules-jvm-external/coursier.bzl", line 777, column 38, in _coursier_fetch_impl
		dep_tree = make_coursier_dep_tree(
	File "/Users/buildkite/builds/bk-imacpro-20/bazel/rules-jvm-external/coursier.bzl", line 713, column 13, in make_coursier_dep_tree
		fail("Error while fetching artifact with coursier: " + exec_result.stderr)
Error in fail: Error while fetching artifact with coursier: Resolution error: Error downloading org.jboss.weld:weld-api-parent:1.0
  download error: Caught java.net.ConnectException: Operation timed out (Connection timed out) (Operation timed out (Connection timed out)) while downloading https://repo1.maven.org/maven2/org/jboss/weld/weld-api-parent/1.0/weld-api-parent-1.0.pom
  not found: https://maven.google.com/org/jboss/weld/weld-api-parent/1.0/weld-api-parent-1.0.pom
  not found: https://packages.confluent.io/maven/org/jboss/weld/weld-api-parent/1.0/weld-api-parent-1.0.pom
Error downloading javax.inject:javax.inject:
  not found: https://repo1.maven.org/maven2/javax/inject/javax.inject//javax.inject-.pom
  not found: https://maven.google.com/javax/inject/javax.inject//javax.inject-.pom
  not found: https://packages.confluent.io/maven/javax/inject/javax.inject//javax.inject-.pom
Error downloading javax.annotation:jsr250-api:
  not found: https://repo1.maven.org/maven2/javax/annotation/jsr250-api//jsr250-api-.pom
  not found: https://maven.google.com/javax/annotation/jsr250-api//jsr250-api-.pom
  not found: https://packages.confluent.io/maven/javax/annotation/jsr250-api//jsr250-api-.pom
```

Looks like some Maven infra change is the cause of the failure?

**Comment by meteorcloudy** [comment]
Looks like the infra failure has gone away in latest builds:
https://buildkite.com/bazel/rules-jvm-external/builds/2007
