### ISSUE TITLE
Unauthorized Error: using private maven repo to existing android project

### ISSUE THREAD

**Issue by heeh** [bazelbuild/rules_jvm_external#632]
I followed the `README.md` I got an error while I am using `bazel build` . 
Is there anything I need to do when I use the coursier property file?
Or, am I missing something?

**ERROR**
```bash
ERROR: An error occurred during the fetch of repository 'maven':
   Traceback (most recent call last):
        File "/home/heeh/.cache/bazel/_bazel_heeh/d49e99ec84b50cbdd33c9d4ee0855451/external/rules_jvm_external/coursier.bzl", line 846, column 38, in _coursier_fetch_impl
                dep_tree = make_coursier_dep_tree(
        File "/home/heeh/.cache/bazel/_bazel_heeh/d49e99ec84b50cbdd33c9d4ee0855451/external/rules_jvm_external/coursier.bzl", line 777, column 13, in make_coursier_dep_tree
                fail("Error while fetching artifact with coursier: " + exec_result.stderr)
Error in fail: Error while fetching artifact with coursier: Resolution error: Error downloading com.foobar:1.1.0
  unauthorized: https://artifacts.azena.com/repository/maven/com/foobar/XXX/YYY/1.1.0/ZZZ-1.1.0.pom (Sonatype Nexus Repository Manager)
```

**./config/coursier/credentials.properties**
```
simple.username=foo@bar.com
simple.password=xxx:;:;yyy:;zzz
simple.host=artifacts.foobar.com/repository/maven
```

**WORKSPACE**
```bazel
load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

RULES_JVM_EXTERNAL_TAG = "4.2"
RULES_JVM_EXTERNAL_SHA = "cd1a77b7b02e8e008439ca76fd34f5b07aecb8c752961f9640dea15e9e5ba1ca"

http_archive(
    name = "rules_jvm_external",
    strip_prefix = "rules_jvm_external-%s" % RULES_JVM_EXTERNAL_TAG,
    sha256 = RULES_JVM_EXTERNAL_SHA,
    url = "https://github.com/bazelbuild/rules_jvm_external/archive/%s.zip" % RULES_JVM_EXTERNAL_TAG,
)

load("@rules_jvm_external//:defs.bzl", "maven_install")

maven_install(
    artifacts = [
        "foo:bar:0.0.1",
    ],
    repositories = [
        # Private repositories are supported through HTTP Basic auth
        "http://artifacts.foo.com/repository/maven",
    ],
)
```

**BUILD**
```bazel
java_library(
    name = "java_test_deps",
    exports = [
        "@maven//:foo_bar",
    ],
)

android_library(
    name = "android_test_deps",
    exports = [
        "@maven//:foo_bar",
    ],
)
```

**Comment by heeh** [comment]
Nevermind, I did not include the repository in a right place :)
