### ISSUE TITLE
"Error while trying to parse the path of file in the coursier cache" when XDG_CACHE_HOME environment variable is set

### ISSUE THREAD

**Issue by beasleyr-vmw** [bazelbuild/rules_jvm_external#638]
Coursier honors the [XDG Base Directory Specification](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html)'s `XDG_CACHE_HOME` as a replacement for `$HOME/.cache`. (Example use case: Home directory is mounted via NFS.) However, rules_jvm_external is broken since v3.3 for any user relying on this feature:

```console
$ XDG_CACHE_HOME=/tmp/.cache bazelisk test //tests/integration:guava_import
...
ERROR: An error occurred during the fetch of repository 'unsafe_shared_cache':
   Traceback (most recent call last):
        File "/work/third_party/rules_jvm_external/coursier.bzl", line 924, column 66, in _coursier_fetch_impl
                artifact.update({"file": _relativize_and_symlink_file(repository_ctx, artifact["file"])})
        File "/work/third_party/rules_jvm_external/coursier.bzl", line 152, column 13, in _relativize_and_symlink_file
                fail("Error while trying to parse the path of file in the coursier cache: " + absolute_path)
Error in fail: Error while trying to parse the path of file in the coursier cache: /tmp/.cache/coursier/v1/https/repo1.maven.org/maven2/com/google/code/findbugs/jsr305/3.0.2/jsr305-3.0.2-sources.jar
ERROR: Error fetching repository: Traceback (most recent call last):
        File "/work/third_party/rules_jvm_external/coursier.bzl", line 924, column 66, in _coursier_fetch_impl
                artifact.update({"file": _relativize_and_symlink_file(repository_ctx, artifact["file"])})
        File "/work/third_party/rules_jvm_external/coursier.bzl", line 152, column 13, in _relativize_and_symlink_file
                fail("Error while trying to parse the path of file in the coursier cache: " + absolute_path)
Error in fail: Error while trying to parse the path of file in the coursier cache: /tmp/.cache/coursier/v1/https/repo1.maven.org/maven2/com/google/code/findbugs/jsr305/3.0.2/jsr305-3.0.2-sources.jar
ERROR: /work/third_party/rules_jvm_external/tests/integration/BUILD:78:12: //tests/integration:guava_import depends on @unsafe_shared_cache//:v1/https/repo1.maven.org/maven2/com/google/guava/guava/27.0-jre/guava-27.0-jre.jar in repository @unsafe_shared_cache which failed to fetch. no such package '@unsafe_shared_cache//': Error while trying to parse the path of file in the coursier cache: /tmp/.cache/coursier/v1/https/repo1.maven.org/maven2/com/google/code/findbugs/jsr305/3.0.2/jsr305-3.0.2-sources.jar
ERROR: Analysis of target '//tests/integration:guava_import' failed; build aborted: Analysis failed
INFO: Elapsed time: 9.722s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (1 packages loaded, 1 target configured)
FAILED: Build did NOT complete successfully (1 packages loaded, 1 target configured)
```

I believe that this is a result of #407 and related PRs which aren't aware of the `XDG_CACHE_HOME` behavior:
https://github.com/bazelbuild/rules_jvm_external/blob/cb3627c1ef5d5baaa6e91163ebd9bc0e00c74d38/coursier.bzl#L657-L669

**Comment by beasleyr-vmw** [comment]
Coursier derives directory roots using the [dirs-dev/directories-jvm](https://github.com/dirs-dev/directories-jvm) package's [PackageDirectories](https://github.com/dirs-dev/directories-jvm/tree/006ca7ff804ca48f692d59a7fce8599f8a1eadfc#projectdirectories). So it seems as though `XDG_CACHE_HOME` is honored on Linux/BSD/Solaris/etc. (i.e. everything except Windows and macOS).
