### ISSUE TITLE
Failed to resolve deps for com.google.firebase:firebase-firestore

### ISSUE THREAD

**Issue by senpo** [bazelbuild/rules_jvm_external#70]
Steps to reproduce:

* Modify [the simple example inside this rules_jvm_external repo](
https://github.com/bazelbuild/rules_jvm_external/tree/master/examples/simple) and try using the firebase-firestore.
* Edit WORKSPACE file, add "com.google.firebase:firebase-firestore:18.1.0" to the artifact list.
```
load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

android_sdk_repository(name = "androidsdk")

local_repository(
    name = "rules_jvm_external",
    path = "../../",
)

load("@rules_jvm_external//:defs.bzl", "maven_install")

maven_install(
    artifacts = [ 
        "junit:junit:4.12",
        "android.arch.lifecycle:common:1.1.1",
        "android.arch.lifecycle:viewmodel:1.1.1",
        "androidx.test.espresso:espresso-web:3.1.1",
        "com.android.support:design:27.0.2",
        "com.google.firebase:firebase-firestore:18.1.0",
    ],  
    repositories = [ 
        "https://maven.google.com",
        "https://repo1.maven.org/maven2",
    ],  
)
```

* Edit BUILD file to add the artifact("com.google.firebase:firebase-firestore") line.
```
load("@rules_jvm_external//:defs.bzl", "artifact")

android_library(
    name = "my_lib",
    exports = [ 
        artifact("android.arch.lifecycle:common"),
        artifact("android.arch.lifecycle:viewmodel"),
        artifact("androidx.test.espresso:espresso-web"),
        artifact("junit:junit"),
        artifact("com.android.support:design"),
        artifact("com.google.firebase:firebase-firestore"),
    ],  
)

android_binary(
    name = "my_app",
    custom_package = "com.example.bazel",
    manifest = "AndroidManifest.xml",
    deps = [":my_lib"],
)
```

* Run bazel build :my_app and see the following error:
```
ERROR: /Users/senpo/Sources/github/bazelbuild/rules_jvm_external/examples/simple/BUILD:3:1: no such package '@maven//': Traceback (most recent call last):
	File "/private/var/tmp/_bazel_senpo/d029bda8bea034c8607a9968bc5c1c7e/external/rules_jvm_external/coursier.bzl", line 374
		generate_imports(repository_ctx = repository_ctx, d..., ...)
	File "/private/var/tmp/_bazel_senpo/d029bda8bea034c8607a9968bc5c1c7e/external/rules_jvm_external/coursier.bzl", line 228, in generate_imports
		fail((((("The artifact for " + artifa...)))
The artifact for io.grpc:grpc-android:jar:1.16.1 was not downloaded. Perhaps the packaging type is not one of: jar, aar, bundle?
Parsed artifact data:{"coord": "io.grpc:grpc-android:jar:1.16.1", "file": None, "dependencies": ["io.opencensus:opencensus-contrib-grpc-metrics:0.12.3", "com.google.code.findbugs:jsr305:3.0.2", "io.grpc:grpc-context:1.16.1", "com.google.code.gson:gson:2.7", "io.grpc:grpc-core:1.16.1", "org.checkerframework:checker-compat-qual:2.5.2", "org.codehaus.mojo:animal-sniffer-annotations:1.17", "com.google.j2objc:j2objc-annotations:1.1", "com.google.errorprone:error_prone_annotations:2.2.0", "io.opencensus:opencensus-api:0.12.3", "com.google.guava:guava:26.0-android"]} and referenced by '//:my_lib'
```

**Comment by jin** [comment]
`com.google.firebase:firebase-firestore:18.1.0`'s POM file specifies the packaging type of its dependency, `io.grpc:grpc-android`, incorrectly:

```xml
<?xml version='1.0' encoding='UTF-8'?>
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://maven.apache.org/POM/4.0.0" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>com.google.firebase</groupId>
  <artifactId>firebase-firestore</artifactId>
  <version>18.1.0</version>
  <packaging>aar</packaging>
  <dependencies>
    <!-- redacted for clarity -->   
    <dependency>
      <groupId>io.grpc</groupId>
      <artifactId>grpc-android</artifactId>
      <version>1.16.1</version>
      <scope>compile</scope>
      <type>jar</type>
    </dependency>
    <!-- redacted for clarity -->   
  </dependencies>
  <name>firebase-firestore</name>
</project>
```

The `<type>` node should be `aar`: https://mvnrepository.com/artifact/io.grpc/grpc-android/1.18.0

This needs to be fixed upstream, and we should also fail with a better error. Coursier did successfully fetch the POM file to resolve grpc-android's deps, but it should fail by saying that the packaging type may be specified incorrectly in the POM file.

**Comment by senpo** [comment]
Thanks. I just filed https://github.com/firebase/firebase-android-sdk/issues/292

This build tool is so amazing. Given firebase is such a foundational lib, I'm curious whether we could provide a little bit fault tolerance to mitigate this issue which seriously blocking any kind of real-world android app development before any upstream fix arrives without falling back to Gradle. 

The feature request option #1: Have the coursier somehow try to fetch aar type whenever a jar request timeout. It's transparent to users. Maybe gradle is doing the same to handle the faulty pom config.

The option #2: Allow users to override the pom file with the maven.artifact helper so people can correct the pom config locally and keep the build going before the upstream fix is released.

Thanks and much appreciated!

**Comment by jin** [comment]
We should reduce surprises as much as possible, and not have implicit workarounds for upstream errors. 

That means that option B is a better idea than A. Option A leads us into a space where we have multiple bundle types to think about, and other failure modes that are not necessarily related to the original mistake in the POM file.

Exposing a POM file replacement API sounds powerful, almost a bit too powerful (and I don't think it works with Coursier in the first place) :) 

The Coursier CLI has an option called `--intransitive` that accepts a list of artifacts. These artifacts will be fetched additionally even if they're not in the transitive dependencies of the requested artifacts. I just verified that while 

```
$ third_party/coursier/coursier fetch "com.google.firebase:firebase-firestore:18.1.0" -r https://maven.google.com -A jar,aar,bundle | grep grpc-android
```

does not contain the grpc-android artifact, setting `--intransitive io.grpc:grpc-android:1.16.1` does download it:

```
$ third_party/coursier/coursier fetch "com.google.firebase:firebase-firestore:18.1.0" -r https://maven.google.com -A jar,aar,bundle --intransitive io.grpc:grpc-android:1.16.1 | grep grpc-android
/usr/local/google/home/jingwen/.cache/coursier/v1/https/repo1.maven.org/maven2/io/grpc/grpc-android/1.16.1/grpc-android-1.16.1.aar
```

It's possible that we can expose `--intransitive` as an attribute in `maven_install` to download the artifact. However, this still doesn't fix the problem that Coursier believes the upstream POM and wires its internal dep graph using the bad dep anyway:

```json
{
      "coord": "com.google.firebase:firebase-firestore:18.1.0",
      "file": "/usr/local/google/home/jingwen/.cache/coursier/v1/https/maven.google.com/com/google/firebase/firebase-firestore/18.1.0/firebase-firestore-18.1.0.aar",
      "dependencies": [
         ...
        "io.grpc:grpc-android:jar:1.16.1",
         ...
      ]
},
```

All that said, I still think the onus is on the upstream to fix the POM files, and I'm not sure what's the best way forward here other than upstreaming patches to Coursier itself.

**Comment by jin** [comment]
I have a WIP branch that prints this new error message if Coursier fails to download a file:

```
ERROR: no such package '@regression_tested_artifacts//': Traceback (most recent call last):
	File "/usr/local/google/home/jingwen/.cache/bazel/_bazel_jingwen/8484bc4fff18ee4a905b69a9ddb0e143/external/rules_jvm_external/coursier.bzl", line 416
		generate_imports(repository_ctx = repository_ctx, d..., ...)
	File "/usr/local/google/home/jingwen/.cache/bazel/_bazel_jingwen/8484bc4fff18ee4a905b69a9ddb0e143/external/rules_jvm_external/coursier.bzl", line 267, in generate_imports
		fail(error_message)

The artifact for io.grpc:grpc-android:jar:1.16.1 was not downloaded. Perhaps its packaging type is not one of: jar,aar,bundle,eclipse-plugin?

These artifact(s) depend on io.grpc:grpc-android:jar:1.16.1:

com.google.firebase:firebase-firestore:18.1.0

It is also possible that the type of io.grpc:grpc-android:jar:1.16.1 is specified incorrectly in the POM file of the artifact that depends on it. For example, io.grpc:grpc-android:jar:1.16.1 may be an AAR, but the dependent's POM file specified its `<type>` value to be a JAR.

Parsed artifact data: {"coord": "io.grpc:grpc-android:jar:1.16.1", "file": None, "dependencies": ["io.opencensus:opencensus-contrib-grpc-metrics:0.12.3", "com.google.code.findbugs:jsr305:3.0.2", "io.grpc:grpc-context:1.16.1", "com.google.code.gson:gson:2.7", "io.grpc:grpc-core:1.16.1", "org.checkerframework:checker-compat-qual:2.5.2", "org.codehaus.mojo:animal-sniffer-annotations:1.17", "com.google.j2objc:j2objc-annotations:1.1", "com.google.errorprone:error_prone_annotations:2.2.0", "io.opencensus:opencensus-api:0.12.3", "com.google.guava:guava:26.0-android"]}
            
Loading: 0 packages loaded
    Fetching @regression_tested_artifacts; Generating BUILD targets.. 23s
```

**Comment by senpo** [comment]
Thanks for the investigation. The new error message looks nice and is definitely more helpful. If there was no reasonable low-hanging workaround, I agree that the best way forward is the upstream fix as firebase folks has committed to it.

**Comment by jin** [comment]
Fixed with `com.google.firebase:firebase-firestore:19.0.0`:

```
maven_install(
    artifacts = [
        "com.google.firebase:firebase-firestore:19.0.0",
    ],
    repositories = [
        "https://maven.google.com",
        "https://repo1.maven.org/maven2",
    ],
)
```

```
$ bazel query @maven//:all
@maven//:org_codehaus_mojo_animal_sniffer_annotations_1_17
@maven//:org_checkerframework_checker_compat_qual_2_5_2
@maven//:io_opencensus_opencensus_contrib_grpc_metrics_0_12_3
@maven//:io_opencensus_opencensus_api_0_12_3
@maven//:io_grpc_grpc_stub_1_16_1
@maven//:io_grpc_grpc_protobuf_lite_1_16_1
@maven//:io_grpc_grpc_okhttp_1_16_1
@maven//:io_grpc_grpc_core_1_16_1
@maven//:io_grpc_grpc_context_1_16_1
@maven//:io_grpc_grpc_android_1_16_1
@maven//:com_squareup_okio_okio_1_13_0
@maven//:com_squareup_okhttp_okhttp_2_7_5
@maven//:com_google_protobuf_protobuf_lite_3_0_1
@maven//:com_google_j2objc_j2objc_annotations_1_1
@maven//:com_google_guava_listenablefuture_9999_0_empty_to_avoid_conflict_with_guava
@maven//:com_google_guava_guava_26_0_android
@maven//:com_google_firebase_protolite_well_known_types_16_0_1
@maven//:com_google_firebase_firebase_firestore_19_0_0
@maven//:com_google_firebase_firebase_firestore
@maven//:io_grpc_grpc_stub
@maven//:io_grpc_grpc_protobuf_lite
@maven//:io_grpc_grpc_okhttp
@maven//:io_grpc_grpc_android
@maven//:io_grpc_grpc_core
@maven//:org_codehaus_mojo_animal_sniffer_annotations
@maven//:io_opencensus_opencensus_contrib_grpc_metrics
@maven//:io_opencensus_opencensus_api
@maven//:io_grpc_grpc_context
@maven//:com_squareup_okhttp_okhttp
@maven//:com_squareup_okio_okio
@maven//:com_google_guava_listenablefuture
@maven//:com_google_guava_guava
@maven//:org_checkerframework_checker_compat_qual
@maven//:com_google_j2objc_j2objc_annotations
@maven//:com_google_firebase_protolite_well_known_types
@maven//:com_google_protobuf_protobuf_lite
@maven//:com_google_firebase_firebase_database_collection_16_0_1
@maven//:com_google_firebase_firebase_database_collection
@maven//:com_google_firebase_firebase_common_17_0_0
@maven//:com_google_firebase_firebase_auth_interop_17_0_0
@maven//:com_google_firebase_firebase_auth_interop
@maven//:com_google_firebase_firebase_common
@maven//:com_google_errorprone_error_prone_annotations_2_2_0
@maven//:com_google_errorprone_error_prone_annotations
@maven//:com_google_code_gson_gson_2_7
@maven//:com_google_code_gson_gson
@maven//:com_google_code_findbugs_jsr305_3_0_2
@maven//:com_google_code_findbugs_jsr305
@maven//:com_google_auto_value_auto_value_annotations_1_6_3
@maven//:com_google_auto_value_auto_value_annotations
@maven//:com_google_android_gms_play_services_tasks_16_0_1
@maven//:com_google_android_gms_play_services_basement_16_1_0
@maven//:com_google_android_gms_play_services_base_16_0_1
@maven//:com_google_android_gms_play_services_base
@maven//:com_google_android_gms_play_services_tasks
@maven//:com_google_android_gms_play_services_basement
@maven//:com_android_support_support_v4_26_1_0
@maven//:com_android_support_support_v4
@maven//:com_android_support_support_media_compat_26_1_0
@maven//:com_android_support_support_media_compat
@maven//:com_android_support_support_fragment_26_1_0
@maven//:com_android_support_support_fragment
@maven//:com_android_support_support_core_utils_26_1_0
@maven//:com_android_support_support_core_utils
@maven//:com_android_support_support_core_ui_26_1_0
@maven//:com_android_support_support_core_ui
@maven//:com_android_support_support_compat_26_1_0
@maven//:com_android_support_support_compat
@maven//:com_android_support_support_annotations_26_1_0
@maven//:com_android_support_support_annotations
@maven//:android_arch_lifecycle_runtime_1_0_0
@maven//:android_arch_lifecycle_runtime
@maven//:android_arch_lifecycle_common_1_0_0
@maven//:android_arch_lifecycle_common
@maven//:android_arch_core_common_1_0_0
@maven//:android_arch_core_common
Loading: 1 packages loaded
```
