### ISSUE TITLE
Bazel build for SpringBoot fails with "No auto configuration classes found in META-INF/spring.factories"

### ISSUE THREAD

**Issue by xushaoxiao** [bazelbuild/rules_jvm_external#706]
A build is created as
```shell
bazel build //cover:cover_deploy.jar
```
Trying to execute as `java -jar bazel-bin/cover/cover_deploy.jar` results in following output:
```text
LCNC02GG727MD6R:big-gov-mono shaoxixu$ java -jar bazel-bin/cover/cover_deploy.jar
ERROR StatusLogger Unrecognized format specifier [d]
ERROR StatusLogger Unrecognized conversion specifier [d] starting at position 16 in conversion pattern.
ERROR StatusLogger Unrecognized format specifier [thread]
ERROR StatusLogger Unrecognized conversion specifier [thread] starting at position 25 in conversion pattern.
ERROR StatusLogger Unrecognized format specifier [level]
ERROR StatusLogger Unrecognized conversion specifier [level] starting at position 35 in conversion pattern.
ERROR StatusLogger Unrecognized format specifier [logger]
ERROR StatusLogger Unrecognized conversion specifier [logger] starting at position 47 in conversion pattern.
ERROR StatusLogger Unrecognized format specifier [msg]
ERROR StatusLogger Unrecognized conversion specifier [msg] starting at position 54 in conversion pattern.
ERROR StatusLogger Unrecognized format specifier [n]
ERROR StatusLogger Unrecognized conversion specifier [n] starting at position 56 in conversion pattern.
ERROR StatusLogger Unrecognized format specifier [d]

  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::                        

%d [%thread] %-5level %logger - %msg%n java.lang.IllegalArgumentException: No auto configuration classes found in META-INF/spring.factories. If you are using a custom packaging, make sure that file is correct.
        at org.springframework.util.Assert.notEmpty(Assert.java:470) ~[cover_deploy.jar:?]
        at org.springframework.boot.autoconfigure.AutoConfigurationImportSelector.getCandidateConfigurations(AutoConfigurationImportSelector.java:180) ~[cover_deploy.jar:?]
        at org.springframework.boot.autoconfigure.AutoConfigurationImportSelector.getAutoConfigurationEntry(AutoConfigurationImportSelector.java:123) ~[cover_deploy.jar:?]
        at org.springframework.boot.autoconfigure.AutoConfigurationImportSelector$AutoConfigurationGroup.process(AutoConfigurationImportSelector.java:434) ~[cover_deploy.jar:?]
        at org.springframework.context.annotation.ConfigurationClassParser$DeferredImportSelectorGrouping.getImports(ConfigurationClassParser.java:879) ~[cover_deploy.jar:?]
        at org.springframework.context.annotation.ConfigurationClassParser$DeferredImportSelectorGroupingHandler.processGroupImports(ConfigurationClassParser.java:809) ~[cover_deploy.jar:?]
        at org.springframework.context.annotation.ConfigurationClassParser$DeferredImportSelectorHandler.process(ConfigurationClassParser.java:780) ~[cover_deploy.jar:?]
        at org.springframework.context.annotation.ConfigurationClassParser.parse(ConfigurationClassParser.java:193) ~[cover_deploy.jar:?]
        at org.springframework.context.annotation.ConfigurationClassPostProcessor.processConfigBeanDefinitions(ConfigurationClassPostProcessor.java:331) ~[cover_deploy.jar:?]
        at org.springframework.context.annotation.ConfigurationClassPostProcessor.postProcessBeanDefinitionRegistry(ConfigurationClassPostProcessor.java:247) ~[cover_deploy.jar:?]
        at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanDefinitionRegistryPostProcessors(PostProcessorRegistrationDelegate.java:311) ~[cover_deploy.jar:?]
        at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:112) ~[cover_deploy.jar:?]
        at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:746) ~[cover_deploy.jar:?]
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:564) ~[cover_deploy.jar:?]
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:145) ~[cover_deploy.jar:?]
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:740) ~[cover_deploy.jar:?]
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:415) ~[cover_deploy.jar:?]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:303) ~[cover_deploy.jar:?]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1312) ~[cover_deploy.jar:?]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1301) ~[cover_deploy.jar:?]
```

**Comment by xushaoxiao** [comment]
`bazel run //cover:cover` is work successfully.

**Comment by xushaoxiao** [comment]
`bazel run //cover:cover` is work successfully.
