### ISSUE TITLE
rules_jvm_external is flaky on Bazel CI with Bazel 5.3.0

### ISSUE THREAD

**Issue by meteorcloudy** [bazelbuild/rules_jvm_external#745]
https://buildkite.com/bazel/rules-jvm-external/builds/2863#0183343b-7e38-4000-9d63-fa5cabe366f8
```
INFO: Found 1 target...
ERROR: /var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite-agent/ec321eb2cc2d0f8f91b676b6d4c66c29/external/rules_jvm_external_deps/BUILD:1164:11: Creating compile jar for @rules_jvm_external_deps//:javax_annotation_javax_annotation_api [for host] failed: (Aborted): AddJarManifestEntry failed: error executing command bazel-out/host/bin/private/tools/java/rules/jvm/external/jar/AddJarManifestEntry --source ... (remaining 6 arguments skipped)
 
Use --sandbox_debug to see verbose messages from the sandbox and retain the sandbox build root for debugging
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGBUS (0x7) at pc=0x00007f5551ee3807, pid=2, tid=3
#
# JRE version:  (11.0.12+7) (build )
# Java VM: OpenJDK 64-Bit Server VM (11.0.12+7-LTS, mixed mode, sharing, tiered, compressed oops, g1 gc, linux-amd64)
# Problematic frame:
# V  [libjvm.so+0xcd8807]  PerfMemory::alloc(unsigned long)+0x57
#
# Core dump will be written. Default location: Core dumps may be processed with "/usr/share/apport/apport %p %s %c %d %P %E" (or dumping to /var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite-agent/ec321eb2cc2d0f8f91b676b6d4c66c29/sandbox/linux-sandbox/100/execroot/rules_jvm_external/core.2)
#
# An error report file with more information is saved as:
# /var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite-agent/ec321eb2cc2d0f8f91b676b6d4c66c29/sandbox/linux-sandbox/100/execroot/rules_jvm_external/hs_err_pid2.log
#
#
Target //tests/integration/kt_jvm_export:test.publish failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 9.723s, Critical Path: 4.61s
INFO: 159 processes: 48 internal, 105 linux-sandbox, 6 worker.
FAILED: Build did NOT complete successfully
FAILED: Build did NOT complete successfully
ERROR
cat: /tmp/test_m2local_testing_found_local_artifact_through_pin_test.log: No such file or directory
Traceback (most recent call last):
  File "bazelci.py", line 3582, in <module>
    sys.exit(main())
  File "bazelci.py", line 3562, in main
    bazel_version=task_config.get("bazel") or configs.get("bazel"),
  File "bazelci.py", line 1287, in execute_commands
    execute_shell_commands(task_config.get("shell_commands", None))
  File "bazelci.py", line 1712, in execute_shell_commands
    execute_command([shell_command], shell=True)
  File "bazelci.py", line 2253, in execute_command
    args, shell=shell, check=fail_if_nonzero, env=os.environ, cwd=cwd
  File "/usr/lib/python3.6/subprocess.py", line 438, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['set -e\nbazel run @unpinned_regression_testing//:pin\nbazel run @unpinned_maven_install_in_custom_location//:pin\nbazel run @duplicate_artifacts_test//:pin\ntests/bazel_run_tests.sh']' returned non-zero exit status 1.
```

A follow up rerun succeeded. /cc @shs96c

**Comment by zabhi** [comment]
Can confirm this. I have a scala build failing thrice for a different dep every time.

```
23:57:15 2022/10/10 18:27:15 INFO    : ERROR: /grid/0/jenkins/.cache/bazel/_bazel_jenkins/9fd8f332825bb1687745f66724c50b98/external/maven/BUILD:1192:11: Creating compile jar for @maven//:commons_io_commons_io failed: (Aborted): AddJarManifestEntry failed: error executing command bazel-out/k8-opt-exec-2B5CBBC6/bin/external/rules_jvm_external/private/tools/java/rules/jvm/external/jar/AddJarManifestEntry --source ... (remaining 6 arguments skipped)
23:57:15 2022/10/10 18:27:15 INFO    : 
23:57:15 2022/10/10 18:27:15 INFO    : Use --sandbox_debug to see verbose messages from the sandbox and retain the sandbox build root for debugging
23:57:15 2022/10/10 18:27:15 INFO    : #
23:57:15 2022/10/10 18:27:15 INFO    : # A fatal error has been detected by the Java Runtime Environment:
23:57:15 2022/10/10 18:27:15 INFO    : #
23:57:15 2022/10/10 18:27:15 INFO    : #  SIGBUS (0x7) at pc=0x00007f90c97899c4, pid=2, tid=3
23:57:15 2022/10/10 18:27:15 INFO    : #
23:57:15 2022/10/10 18:27:15 INFO    : # JRE version:  (11.0.12+7) (build )
23:57:15 2022/10/10 18:27:15 INFO    : # Java VM: OpenJDK 64-Bit Server VM (11.0.12+7-LTS, mixed mode, sharing, tiered, compressed oops, g1 gc, linux-amd64)
23:57:15 2022/10/10 18:27:15 INFO    : # Problematic frame:
23:57:15 2022/10/10 18:27:15 INFO    : # C  [libc.so.6+0x8f9c4]  __memset_sse2+0x54
23:57:15 2022/10/10 18:27:15 INFO    : #
23:57:15 2022/10/10 18:27:15 INFO    : # Core dump will be written. Default location: Core dumps may be processed with "/usr/lib/systemd/systemd-coredump %P %u %g %s %t %c %h %e" (or dumping to /grid/0/jenkins/.cache/bazel/_bazel_jenkins/9fd8f332825bb1687745f66724c50b98/sandbox/linux-sandbox/475/execroot/jumpgate/core.2)
23:57:15 2022/10/10 18:27:15 INFO    : #
23:57:15 2022/10/10 18:27:15 INFO    : # An error report file with more information is saved as:
23:57:15 2022/10/10 18:27:15 INFO    : # /grid/0/jenkins/.cache/bazel/_bazel_jenkins/9fd8f332825bb1687745f66724c50b98/sandbox/linux-sandbox/475/execroot/jumpgate/hs_err_pid2.log
23:57:15 2022/10/10 18:27:15 INFO    : #
23:57:15 2022/10/10 18:27:15 INFO    : #
```

```
10:10:46 2022/10/10 04:40:46 INFO    : ERROR: /grid/0/jenkins/.cache/bazel/_bazel_jenkins/9fd8f332825bb1687745f66724c50b98/external/maven/BUILD:2029:11: Creating compile jar for @maven//:io_spray_spray_json_2_12 failed: (Aborted): AddJarManifestEntry failed: error executing command bazel-out/k8-opt-exec-2B5CBBC6/bin/external/rules_jvm_external/private/tools/java/rules/jvm/external/jar/AddJarManifestEntry --source ... (remaining 6 arguments skipped)
10:10:46 2022/10/10 04:40:46 INFO    : 
10:10:46 2022/10/10 04:40:46 INFO    : Use --sandbox_debug to see verbose messages from the sandbox and retain the sandbox build root for debugging
10:10:46 2022/10/10 04:40:46 INFO    : #
10:10:46 2022/10/10 04:40:46 INFO    : # A fatal error has been detected by the Java Runtime Environment:
10:10:46 2022/10/10 04:40:46 INFO    : #
10:10:46 2022/10/10 04:40:46 INFO    : #  SIGBUS (0x7) at pc=0x00007f01fa83c9c4, pid=2, tid=3
10:10:46 2022/10/10 04:40:46 INFO    : #
10:10:46 2022/10/10 04:40:46 INFO    : # JRE version:  (11.0.12+7) (build )
10:10:46 2022/10/10 04:40:46 INFO    : # Java VM: OpenJDK 64-Bit Server VM (11.0.12+7-LTS, mixed mode, sharing, tiered, compressed oops, g1 gc, linux-amd64)
10:10:46 2022/10/10 04:40:46 INFO    : # Problematic frame:
10:10:46 2022/10/10 04:40:46 INFO    : # C  [libc.so.6+0x8f9c4]  __memset_sse2+0x54
10:10:46 2022/10/10 04:40:46 INFO    : #
10:10:46 2022/10/10 04:40:46 INFO    : # Core dump will be written. Default location: Core dumps may be processed with "/usr/lib/systemd/systemd-coredump %P %u %g %s %t %c %h %e" (or dumping to /grid/0/jenkins/.cache/bazel/_bazel_jenkins/9fd8f332825bb1687745f66724c50b98/sandbox/linux-sandbox/521/execroot/jumpgate/core.2)
10:10:46 2022/10/10 04:40:46 INFO    : #
10:10:46 2022/10/10 04:40:46 INFO    : # An error report file with more information is saved as:
10:10:46 2022/10/10 04:40:46 INFO    : # /grid/0/jenkins/.cache/bazel/_bazel_jenkins/9fd8f332825bb1687745f66724c50b98/sandbox/linux-sandbox/521/execroot/jumpgate/hs_err_pid2.log
10:10:46 2022/10/10 04:40:46 INFO    : #
10:10:46 2022/10/10 04:40:46 INFO    : #
10:
```

```
18:19:08 2022/10/09 12:49:08 INFO    : ERROR: /grid/0/jenkins/.cache/bazel/_bazel_jenkins/9fd8f332825bb1687745f66724c50b98/external/maven/BUILD:347:11: Creating compile jar for @maven//:com_google_guava_guava failed: (Aborted): AddJarManifestEntry failed: error executing command bazel-out/k8-opt-exec-2B5CBBC6/bin/external/rules_jvm_external/private/tools/java/rules/jvm/external/jar/AddJarManifestEntry --source ... (remaining 6 arguments skipped)
18:19:08 2022/10/09 12:49:08 INFO    : 
18:19:08 2022/10/09 12:49:08 INFO    : Use --sandbox_debug to see verbose messages from the sandbox and retain the sandbox build root for debugging
18:19:08 2022/10/09 12:49:08 INFO    : #
18:19:08 2022/10/09 12:49:08 INFO    : # A fatal error has been detected by the Java Runtime Environment:
18:19:08 2022/10/09 12:49:08 INFO    : #
18:19:08 2022/10/09 12:49:08 INFO    : #  SIGBUS (0x7) at pc=0x00007f0811e389c4, pid=2, tid=3
18:19:08 2022/10/09 12:49:08 INFO    : #
18:19:08 2022/10/09 12:49:08 INFO    : # JRE version:  (11.0.12+7) (build )
18:19:08 2022/10/09 12:49:08 INFO    : # Java VM: OpenJDK 64-Bit Server VM (11.0.12+7-LTS, mixed mode, sharing, tiered, compressed oops, g1 gc, linux-amd64)
18:19:08 2022/10/09 12:49:08 INFO    : # Problematic frame:
18:19:08 2022/10/09 12:49:08 INFO    : # C  [libc.so.6+0x8f9c4]  __memset_sse2+0x54
18:19:08 2022/10/09 12:49:08 INFO    : #
18:19:08 2022/10/09 12:49:08 INFO    : # Core dump will be written. Default location: Core dumps may be processed with "/usr/lib/systemd/systemd-coredump %P %u %g %s %t %c %h %e" (or dumping to /grid/0/jenkins/.cache/bazel/_bazel_jenkins/9fd8f332825bb1687745f66724c50b98/sandbox/linux-sandbox/496/execroot/jumpgate/core.2)
18:19:08 2022/10/09 12:49:08 INFO    : #
18:19:08 2022/10/09 12:49:08 INFO    : # An error report file with more information is saved as:
18:19:08 2022/10/09 12:49:08 INFO    : # /grid/0/jenkins/.cache/bazel/_bazel_jenkins/9fd8f332825bb1687745f66724c50b98/sandbox/linux-sandbox/496/execroot/jumpgate/hs_err_pid2.log
18:19:08 2022/10/09 12:49:08 INFO    : #
18:19:08 2022/10/09 12:49:08 INFO    : #
```

**Comment by SalmaSamy** [comment]
Hello @jin, @shs96c,
Can you please check this one

**Comment by meteorcloudy** [comment]
https://buildkite.com/bazel/rules-jvm-external/builds/3073#_
This flaky error has been happening very frequently on Bazel CI, @cheister can help look into it?

**Comment by shs96c** [comment]
We're not sure it's a problem with `rules_jvm_external`: there are no bug reports from users about this problem occurring, yet it seems to happen very frequently on the Build Kite machines. Are we sure it's not a hardware problem of some kind?

**Comment by al-babych-fivetran** [comment]
we have a similar error with Bazel 4.3.2 and rules_jvm_external 4.5 (also flaky)

```
ERROR: /<REDACTED>/.cache/bazel/_bazel_buildkite-agent/ecc999562ecfafc8c5d0898d9fc39774/external/maven/BUILD:16690:11: Creating compile jar for @maven//:com_blueconic_browscap_java failed: (Aborted): AddJarManifestEntry failed: error executing command bazel-out/k8-py2-opt-exec-2B5CBBC6/bin/external/rules_jvm_external/private/tools/java/rules/jvm/external/jar/AddJarManifestEntry --source ... (remaining 6 argument(s) skipped)
--
  |  
  | Use --sandbox_debug to see verbose messages from the sandbox
  | #
  | # A fatal error has been detected by the Java Runtime Environment:
  | #
  | #  SIGBUS (0x7) at pc=0x00007f18c311b0e9, pid=2, tid=3
  | #
  | # JRE version:  (11.0.10+9) (build )
  | # Java VM: OpenJDK 64-Bit Server VM (11.0.10+9-LTS, mixed mode, sharing, tiered, compressed oops, g1 gc, linux-amd64)
  | # Problematic frame:
  | # V  [libjvm.so+0xca70e9]  PerfMemory::alloc(unsigned long)+0x59
  | #
  | # Core dump will be written. Default location: Core dumps may be processed with "/usr/share/apport/apport -p%p -s%s -c%c -d%d -P%P -u%u -g%g -- %E" (or dumping to /<REDACTED>/.cache/bazel/_bazel_buildkite-agent/ecc999562ecfafc8c5d0898d9fc39774/sandbox/linux-sandbox/1150/execroot/fivetran/core.2)
  | #
  | # An error report file with more information is saved as:
  | # /<REDACTED>/.cache/bazel/_bazel_buildkite-agent/ecc999562ecfafc8c5d0898d9fc39774/sandbox/linux-sandbox/1150/execroot/fivetran/hs_err_pid2.log
  | #
  | #
  | Target //<REDACTED> failed to build
  | Use --verbose_failures to see the command lines of failed build steps.
  | ERROR: /<REDACTED>/BUILD:3:13 Building <REDACTED>/libmain.jar (339 source files) failed: (Aborted): AddJarManifestEntry failed: error executing command bazel-out/k8-py2-opt-exec-2B5CBBC6/bin/external/rules_jvm_external/private/tools/java/rules/jvm/external/jar/AddJarManifestEntry --source ... (remaining 6 argument(s) skipped)
  |  


```

**Comment by shs96c** [comment]
#815 should fix this issue.
