### ISSUE TITLE
SNAPSHOT versions not working in LockFileConverter

### ISSUE THREAD

**Issue by Andrius-B** [bazelbuild/rules_jvm_external#901]
I am trying to use a SNAPSHOT artifact and it seems that these are not supported by the `LockFileConverter.java`. Simple reproduction is a WORKSPACE file like so:
```python
workspace(name = "rules_jvm_snapshot_repro")

load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

RULES_JVM_EXTERNAL_TAG = "5.2"

RULES_JVM_EXTERNAL_SHA = "f86fd42a809e1871ca0aabe89db0d440451219c3ce46c58da240c7dcdc00125f"

http_archive(
    name = "rules_jvm_external",
    sha256 = RULES_JVM_EXTERNAL_SHA,
    strip_prefix = "rules_jvm_external-%s" % RULES_JVM_EXTERNAL_TAG,
    url = "https://github.com/bazelbuild/rules_jvm_external/releases/download/%s/rules_jvm_external-%s.tar.gz" % (RULES_JVM_EXTERNAL_TAG, RULES_JVM_EXTERNAL_TAG),
)

load("@rules_jvm_external//:repositories.bzl", "rules_jvm_external_deps")

rules_jvm_external_deps()

load("@rules_jvm_external//:setup.bzl", "rules_jvm_external_setup")

rules_jvm_external_setup()

load("@rules_jvm_external//:defs.bzl", "maven_install")

maven_install(
    artifacts = [
        "com.sample.test:sample:0.0.1-SNAPSHOT",
    ],
    repositories = [
        "<internal repository for development>",
    ],
)
```
This sample throws an error from 
```
ERROR: An error occurred during the fetch of repository 'maven':
   Traceback (most recent call last):
        File "/private/var/tmp/_bazel_user/ca5242ff51dc74867dfe3863fbdac862/external/rules_jvm_external/coursier.bzl", line 1054, column 13, in _coursier_fetch_impl
                fail("Unable to generate lock file: " + result.stderr)
Error in fail: Unable to generate lock file: OpenJDK 64-Bit Server VM warning: Options -Xverify:none and -noverify were deprecated in JDK 13 and will likely be removed in a future release.
Exception in thread "main" java.lang.IllegalArgumentException: Expected file name (sample-0.0.1-SNAPSHOT) not found in path (v1/<internal>/repository/java/com/sample/test/sample/0.0.1-SNAPSHOT/sample-0.0.1-20230516.072046-1.jar). Current coordinates are com.sample.test:sample:0.0.1-SNAPSHOT
        at com.github.bazelbuild.rules_jvm_external.coursier.LockFileConverter.deriveCoordinateMappings(LockFileConverter.java:266)
        at com.github.bazelbuild.rules_jvm_external.coursier.LockFileConverter.getDependencies(LockFileConverter.java:113)
        at com.github.bazelbuild.rules_jvm_external.coursier.LockFileConverter.main(LockFileConverter.java:78)
```

The problem is in specifically this part of `LockFileConverter.java` the script:
```java
      // Now we know the version, we can calculate the expected file name. For now, ignore
      // the fact that there may be a classifier. We're going to derive that if necessary.
      String expectedFileName = coord.getArtifactId() + "-" + version;

      index = pathSubstring.indexOf(expectedFileName);
      if (index == -1) {
        throw new IllegalArgumentException(
            String.format(
                "Expected file name (%s) not found in path (%s). Current coordinates are %s",
                expectedFileName, file, coord));
      }
```
In the reproduction case I provided the variables when running this part of the script are set to:
```
pathSubstring="sample-0.0.1-20230516.072046-1.jar"
expectedFileName="sample-0.0.1-SNAPSHOT"
```

it expects the jar file to be named `<mavenName>-<mavenVersion>[-classifier].[extension]` but when using SNAPSHOT's the file name actually the actual SNAPSHOT version. I think the parsing should be updated to first strip the artifact name and then go from back to front in the remainder. I can work on a PR if that approach sounds good.

**Comment by jmmv** [comment]
I'm also hitting this and... is there any workaround? I tried replacing the versions in the `maven_install` rule to be specific and avoid `SNAPSHOT`... but the downloader still seems confused. This is also with `version_conflict_policy="pinned"`, which says that the rule will preserve the version specified in the rule.

**Comment by jmmv** [comment]
I'm not completely sure if the fix is correct, but I've added something here https://github.com/bazelbuild/rules_jvm_external/pull/974 that seems to do the trick for me.

**Comment by vorburger** [comment]
I'm also hitting this issue; see https://github.com/enola-dev/enola/issues/1383.

I consider this almost a P0 blocking issue. Without this, how is one supposed to locally test a fix of a "third party" dependency in another project? Or is there some more Bazel `rules_jvm_external` native way of doing that which I'm not seeing here? (I guess as an extreme workaround one could somehow tempoarily deploy a "release" to a localhost "remote" repo, but that's... no.)

**Comment by vorburger** [comment]
> workaround one could somehow tempoarily deploy a "release" to a localhost "remote" repo

Coming to think of it, the best way to do this is probably just using https://jitpack.io... so for testing you just push local changes of a non-released version to (your fork on) GitHub, have it (JitPack) build the revision, and depend on that "version". I'm actually [doing this in my project](https://github.com/enola-dev/enola/blob/c1cd9bbe978e622a768f3adaac4e6148762f1650/MODULE.bazel#L165), and since #1324 (with `rules_jvm_external` 6.7+, only), that works now.

> Or is there some more Bazel rules_jvm_external native way of doing that which I'm not seeing here?

Would also could be kinda cool would be if `rules_jvm_external` had some way of doing a `git clone` of a random external repo, locally Maven build it for you (only once), locally install the output of that somewhere (preferably outside of `~/.m2`) and then depend on that. So like a Maven equivalent version of an external workspace kinda thing.

**Comment by vinnybod** [comment]
>I consider this almost a P0 blocking issue. Without this, how is one supposed to locally test a fix of a "third party" dependency in another project? Or is there some more Bazel rules_jvm_external native way of doing that which I'm not seeing here?

@vorburger `rules_jvm_external` does have a way to swap in locally built jars.
See https://github.com/bazel-contrib/rules_jvm_external#overriding-generated-targets for the example with WORKSPACE
I didn't see instructions in the repo for bzlmod. I have an example here: https://github.com/vinnybod/blog-examples/tree/main/rules-jvm-external-override

**Comment by shs96c** [comment]
If someone would contribute a patch which allows reproducible builds with snapshot versions, I'd happily merge it.

There are two ways that snapshots seem to be handled by maven repos. The first is by allowing snapshots to be replaced (which would mean excluding the shasum from the `http_file`) and the second is by a redirect to a known coordinate with a date in it. Any solution would need to handle both cases.

**Comment by shs96c** [comment]
> This method makes the build non-reproducible: an artifact that existed in the past and was used as a dependency does not exist anymore because it is replaced by another. I am not sure we need to support this.

We still need to support this, as it's commonly used. Without it, we'd get bug reports pointing out that we don't properly support snapshots, which is the problem we'd like to solve :)

**Comment by friedFat** [comment]
As a Bazel newbie, I came up with the following solution/workaround:

## 1. Apply the following diff

```diff
diff --git a/private/tools/java/com/github/bazelbuild/rules_jvm_external/coursier/LockFileConverter.java b/private/tools/java/com/github/bazelbuild/rules_jvm_external/coursier/LockFileConverter.java
index 9d9c103..e009e06 100644
--- a/private/tools/java/com/github/bazelbuild/rules_jvm_external/coursier/LockFileConverter.java
+++ b/private/tools/java/com/github/bazelbuild/rules_jvm_external/coursier/LockFileConverter.java
@@ -296,7 +296,7 @@ public class LockFileConverter {
 
       // Now we know the version, we can calculate the expected file name. For now, ignore
       // the fact that there may be a classifier. We're going to derive that if necessary.
-      String expectedFileName = coord.getArtifactId() + "-" + version;
+      String expectedFileName = file.substring(file.lastIndexOf('/') + 1, file.lastIndexOf('.'));
 
       index = pathSubstring.indexOf(expectedFileName);
       if (index == -1) {
```

## 2. compile

```shell
bazel build //private/tools/java/com/github/bazelbuild/rules_jvm_external/coursier:LockFileConverter_deploy.jar`
```

## 3. copy the resulting jar to `private/tools/prebuilt/lock_file_converter_deploy.jar`

```shell
cp -f bazel-bin/private/tools/java/com/github/bazelbuild/rules_jvm_external/coursier/LockFileConverter_deploy.jar private/tools/prebuilt/lock_file_converter_deploy.jar  
```

## 4. Use the patched version:

### a) To use a local repository
Add the following to MODULE.bazel:
```python
bazel_dep(name = "rules_jvm_external", version = "7.1")
local_path_override(
    module_name = "rules_jvm_external",
    path = "/path/to/patched/repo", # e.g /home/me/src/rules_jvm_external-patched
)
```

### b) To use a published repository

After pushing the patched repository add the following to MODULE.bazel:
```python
bazel_dep(name = "rules_jvm_external", version = "7.1")
git_override(
    module_name = "rules_jvm_external",
    remote = "http://git.example.com/rules_jvm_external-patched.git"
)
```

## 5. Use SNAPSHOTs

Instead of `com.velocitypowered:velocity-api:4.1.0-SNAPSHOT`, I use `com.velocitypowered:velocity-api:4.1.0-20260802.091736-8`.

Not sure how flexible/robust this solution is but I hope it helps someone.

**Comment by acecilia** [comment]
@friedFat There is a PR here: https://github.com/bazel-contrib/rules_jvm_external/pull/1412
