### ISSUE TITLE
Add support for jvm_import_external rule

### ISSUE THREAD

**Issue by natansil** [bazelbuild/rules_jvm_external#95]
This will allow adding support for others jvm language import rules like scala_import.
CC: @ittaiz

**Comment by jin** [comment]
Right now, the JARs are imported using a basic jvm_import.bzl that exposes a JavaInfo provider for compile_jar, output_jar and source_jar. https://github.com/bazelbuild/rules_jvm_external/blob/master/private/jvm_import.bzl

Does this interop with the Scala rules?

**Comment by ittaiz** [comment]
In theory it does.
In practice we’ll need to see...

**Comment by dgarzon** [comment]
Hi @natansil @ittaiz @jin , I can confirm this is not working with `rules_scala`: dependencies and transitive dependencies are there, but `rules_scala` is not picking them up and fails to compile even really simple applications. I will try to open a PR later today with a minimum reproducible example! Does any of you have an idea why this is not working?

**Comment by jin** [comment]
Please provide a reproducible example here, that will help a lot.

**Comment by dgarzon** [comment]
@jin here you go: https://github.com/dgarzon/rules_jvm_external/tree/EXAMPLE-akka-http-scala. Let me know if I can help with anything else!

**Comment by dgarzon** [comment]
Interestingly, it does seem to find some `import ...`, but fails on others:
```
❯ bazel run app
INFO: Analysed target //:app (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
ERROR: /Users/danielgarzon/Developer/rules_jvm_external/examples/scala/BUILD.bazel:20:1: scala //:lib failed (Exit 1) scalac failed: error executing command bazel-out/darwin-fastbuild/bin/external/io_bazel_rules_scala/src/java/io/bazel/rulesscala/scalac/scalac @bazel-out/darwin-fastbuild/bin/lib_scalac_worker_input

Use --sandbox_debug to see verbose messages from the sandbox
src/main/scala/hello/Configuration.scala:3: error: not found: object pureconfig
import pureconfig._
       ^
src/main/scala/hello/Configuration.scala:4: error: not found: object pureconfig
import pureconfig.generic.auto._
       ^
src/main/scala/hello/Server.scala:3: error: object Http is not a member of package akka.http.scaladsl
import akka.http.scaladsl.Http
       ^
src/main/scala/hello/Server.scala:15: error: not found: value Http
      system: ActorSystem): Future[String \/ Http.ServerBinding] =
                                             ^
src/main/scala/hello/Application.scala:20: error: missing parameter type
      s <- eitherT(Server.start(c.host, c.port, Endpoint.route))
      ^
src/main/scala/hello/Configuration.scala:11: error: not found: value loadConfig
    \/.fromEither(loadConfig[ApplicationConfiguration]("application"))
                  ^
src/main/scala/hello/Endpoint.scala:3: error: object model is not a member of package akka.http.scaladsl
import akka.http.scaladsl.model.{HttpResponse, StatusCodes}
                          ^
src/main/scala/hello/Endpoint.scala:11: error: not found: value HttpResponse
        complete(HttpResponse(StatusCodes.OK))
                 ^
src/main/scala/hello/Endpoint.scala:11: error: not found: value StatusCodes
        complete(HttpResponse(StatusCodes.OK))
                              ^
src/main/scala/hello/Server.scala:16: error: not found: value Http
    Http()
    ^
10 errors found
10 errors found
java.lang.RuntimeException: Build failed
        at io.bazel.rulesscala.scalac.ScalacProcessor.compileScalaSources(ScalacProcessor.java:242)
        at io.bazel.rulesscala.scalac.ScalacProcessor.processRequest(ScalacProcessor.java:67)
        at io.bazel.rulesscala.worker.GenericWorker.run(GenericWorker.java:114)
        at io.bazel.rulesscala.scalac.ScalaCInvoker.main(ScalaCInvoker.java:41)
Target //:app failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 2.826s, Critical Path: 2.68s
INFO: 0 processes.
FAILED: Build did NOT complete successfully
FAILED: Build did NOT complete successfully
```

**Comment by jin** [comment]
@dgarzon updating the list of dependencies to add the direct deps of those missing symbols worked:

```
lib_dependencies = [
   "@maven//:com_github_pureconfig_pureconfig_2_12",
   "@maven//:com_github_pureconfig_pureconfig_core_2_12",
   "@maven//:com_github_pureconfig_pureconfig_generic_2_12",
   "@maven//:com_typesafe_akka_akka_actor_2_12",
   "@maven//:com_typesafe_akka_akka_http_2_12",
   "@maven//:com_typesafe_akka_akka_http_core_2_12",
   "@maven//:com_typesafe_akka_akka_stream_2_12",
   "@maven//:com_typesafe_scala_logging_scala_logging_2_12",
   "@maven//:org_scalaz_scalaz_core_2_12",
   "@maven//:org_scalaz_scalaz_concurrent_2_12",
   "@maven//:org_slf4j_slf4j_api",
   "@maven//:org_slf4j_slf4j_simple",
]
```

Now I'm running into another error:

```
ERROR: /tmp/rules_jvm_external/examples/scala/BUILD.bazel:23:1: scala //:lib failed (Exit 1) scalac failed: error executing command bazel-out/k8-fastbuild/bin/external/io_bazel_rules_scala/src/java/io/bazel/rulesscala/scalac/scalac @bazel-out/k8-fastbuild/bin/lib_scalac_worker_input

Use --sandbox_debug to see verbose messages from the sandbox
src/main/scala/hello/Configuration.scala:11: error: could not find implicit value for parameter reader: pureconfig.Derivation[pureconfig.ConfigReader[hello.ApplicationConfiguration]]
    \/.fromEither(loadConfig[ApplicationConfiguration]("application"))
                                                      ^
one error found
one error found
java.lang.RuntimeException: Build failed
	at io.bazel.rulesscala.scalac.ScalacProcessor.compileScalaSources(ScalacProcessor.java:242)
	at io.bazel.rulesscala.scalac.ScalacProcessor.processRequest(ScalacProcessor.java:67)
	at io.bazel.rulesscala.worker.GenericWorker.run(GenericWorker.java:114)
	at io.bazel.rulesscala.scalac.ScalaCInvoker.main(ScalaCInvoker.java:41)
```

**Comment by jin** [comment]
Got further with tips from https://pureconfig.github.io/docs/faq.html#how-do-i-debug-implicit-not-found-errors

Added `scalacopts = ["-Xmacro-settings:materialize-derivations"],` to `//:lib`, and got:

```
ERROR: /tmp/rules_jvm_external/examples/scala/BUILD.bazel:24:1: scala //:lib failed (Exit 1) scalac failed: error executing command bazel-out/k8-fastbuild/bin/external/io_bazel_rules_scala/src/java/io/bazel/rulesscala/scalac/scalac @bazel-out/k8-fastbuild/bin/lib_scalac_worker_input

Use --sandbox_debug to see verbose messages from the sandbox
src/main/scala/hello/Configuration.scala:13: error: could not find a ConfigReader instance for type ApplicationConfiguration

    \/.fromEither(loadConfig[ApplicationConfiguration](ConfigFactory.empty))
                                                      ^
one error found
one error found
java.lang.RuntimeException: Build failed
	at io.bazel.rulesscala.scalac.ScalacProcessor.compileScalaSources(ScalacProcessor.java:242)
	at io.bazel.rulesscala.scalac.ScalacProcessor.processRequest(ScalacProcessor.java:67)
	at io.bazel.rulesscala.worker.GenericWorker.run(GenericWorker.java:114)
	at io.bazel.rulesscala.scalac.ScalaCInvoker.main(ScalaCInvoker.java:41)
Target //:app failed to build
```

I have no idea what this means.

**Comment by dgarzon** [comment]
Thank you so much @jin! With your guidance I'll be able to take it from here. I'll open a PR once I have it running to leave it as an example for future reference! Awesome job!

**Comment by jin** [comment]
As seen in https://github.com/bazelbuild/rules_jvm_external/pull/100, it looks like these rules already support Scala dependencies. w.r.t ecosystem integration with java_import_external, we can continue the discussion in https://github.com/bazelbuild/rules_jvm_external/issues/85
