### ISSUE TITLE
`is_repin_required() missing 1 required positional argument: repository_ctx` as of commit 687dc35

### ISSUE THREAD

**Issue by rdesgroppes** [bazelbuild/rules_jvm_external#981]
I just gave a try with current master branch (as of commit 687dc3578c1b315e8484a095ff6d4a83e696b21d) and faced:
```sh
$ REPIN=1 bazel run @unpinned_maven//:pin
INFO: Repository maven instantiated at:
  /path/to/WORKSPACE:138:11: in <toplevel>
  /path/to/maven/init.bzl:19:18: in init
  /path/to/external/rules_jvm_external/private/rules/maven_install.bzl:136:30: in maven_install
Repository rule pinned_coursier_fetch defined at:
  /path/to/external/rules_jvm_external/coursier.bzl:1236:40: in <toplevel>
ERROR: An error occurred during the fetch of repository 'maven':
   Traceback (most recent call last):
	File "/path/to/external/rules_jvm_external/coursier.bzl", line 465, column 39, in _pinned_coursier_fetch_impl
		if _fail_if_repin_required(repository_ctx):
	File "/path/to/external/rules_jvm_external/coursier.bzl", line 371, column 29, in _fail_if_repin_required
		return is_repin_required()
	File "/path/to/external/rules_jvm_external/coursier.bzl", line 363, column 5, in is_repin_required
		def is_repin_required(repository_ctx):
Error: is_repin_required() missing 1 required positional argument: repository_ctx
ERROR: /path/to/WORKSPACE:138:11: fetching pinned_coursier_fetch rule //external:maven: Traceback (most recent call last):
	File "/path/to/external/rules_jvm_external/coursier.bzl", line 465, column 39, in _pinned_coursier_fetch_impl
		if _fail_if_repin_required(repository_ctx):
	File "/path/to/external/rules_jvm_external/coursier.bzl", line 371, column 29, in _fail_if_repin_required
		return is_repin_required()
	File "/path/to/external/rules_jvm_external/coursier.bzl", line 363, column 5, in is_repin_required
		def is_repin_required(repository_ctx):
Error: is_repin_required() missing 1 required positional argument: repository_ctx
ERROR: Error computing the main repository mapping: no such package '@maven//': is_repin_required() missing 1 required positional argument: repository_ctx
```
I didn't check what changed yet, but wanted to share it prior to next release.

**Comment by rdesgroppes** [comment]
Might be related to #975, @shs96c?
