### ISSUE TITLE
`unsupported binary operation: string + bool` while evaluating module extension maven in `@rules_jvm_external~5.3//:extensions.bzl`

### ISSUE THREAD

**Issue by agluszak** [bazelbuild/rules_jvm_external#983]
I'm trying to migrate our [project](https://github.com/JetBrains/bazel-bsp/ ) to bzlmod. I managed to fix all errors, but this last strange one from rules_jvm_external remains:

```
ERROR: Traceback (most recent call last):
        File "/home/andrzej/.cache/bazel/_bazel_andrzej/77e3eaab94558fc713e3f88014595919/external/rules_jvm_external~5.3/private/extensions/maven.bzl", line 304, column 52, in _maven_impl
                artifacts_json = [_json.write_artifact_spec(a) for a in artifacts]
        File "/home/andrzej/.cache/bazel/_bazel_andrzej/77e3eaab94558fc713e3f88014595919/external/rules_jvm_external~5.3/specs.bzl", line 230, column 38, in _artifact_spec_to_json
                "\", \"version\": \"" + artifact_spec["version"] + "\""
Error: unsupported binary operation: string + bool
ERROR: Analysis of target '//server/src/main/kotlin/org/jetbrains/bsp/bazel/server:server' failed; build aborted: error evaluating module extension maven in @rules_jvm_external~5.3//:extensions.bzl
INFO: Elapsed time: 0.202s
```

My MODULE.bzl file:

```
module(name = "bazel_bsp", version="")

bazel_dep(name = "bazel_skylib", version = "1.4.2")

# rules_kotlin with bzlmod support have not yet been published to bcr
bazel_dep(name = "rules_kotlin")
git_override(
    module_name = "rules_kotlin",
    remote = "git@github.com:bazelbuild/rules_kotlin.git",
    commit = "55f60ec838a2490d62eac564b437a6c86efee279",
)

BAZEL_VERSION = "7.0.0-pre.20230926.1"

bazel_dep(name = "bazel", repo_name = "io_bazel")
archive_override(
    module_name = "bazel",
    urls = "https://github.com/bazelbuild/bazel/archive/%s.zip" % BAZEL_VERSION,
    strip_prefix = "bazel-%s" % BAZEL_VERSION,
)

# We need to override remoteapis and googleapis because of this:
# https://github.com/bazelbuild/bazel/blob/ea4ab7d8e696f48253fd172fcfbd37661e4710d5/MODULE.bazel#L31

bazel_dep(name = "remoteapis")
archive_override(
    module_name = "remoteapis",
    urls = "https://github.com/bazelbuild/bazel/archive/%s.zip" % BAZEL_VERSION,
    strip_prefix = "bazel-%s/third_party/remoteapis" % BAZEL_VERSION,
)

bazel_dep(name = "googleapis")
archive_override(
    module_name = "googleapis",
    urls = "https://github.com/bazelbuild/bazel/archive/%s.zip" % BAZEL_VERSION,
    strip_prefix = "bazel-%s/third_party/googleapis" % BAZEL_VERSION,
)

bazel_dep(name = "rules_java", version = "6.5.1")
bazel_dep(name = "rules_jvm_external", version = "5.3")
bazel_dep(name = "protobuf", version = "21.7", repo_name = "com_google_protobuf")
bazel_dep(name = "rules_proto", version = "5.3.0-21.7")
bazel_dep(name = "rules_cc", version = "0.0.9")
bazel_dep(name = "platforms", version = "0.0.7")
bazel_dep(name = "rules_python", version = "0.26.0")
# -- bazel_dep definitions -- #

maven = use_extension("@rules_jvm_external//:extensions.bzl", "maven")
maven.install(
    artifacts = [
        "com.google.code.gson:gson:2.10.1",
        "com.google.guava:guava:31.0.1-jre",
        "ch.epfl.scala:bsp4j_2.13:2.1.0-M6.alpha",
        "commons-cli:commons-cli:jar:1.5.0",
        "org.apache.logging.log4j:log4j-api:2.21.0",
        "org.apache.logging.log4j:log4j-core:2.21.0",
        "org.jetbrains.kotlinx:kotlinx-coroutines-core:1.7.3",
        "org.junit.jupiter:junit-jupiter:5.10.0",
        "com.fasterxml.jackson.core:jackson-databind:2.15.3",
        "com.fasterxml.jackson.module:jackson-module-kotlin:2.15.3",
        "com.google.protobuf:protobuf-java:3.24.4",
        "io.grpc:grpc-stub:1.59.0",

        # tests
        "org.junit.jupiter:junit-jupiter-api:5.10.0",
        "org.junit.jupiter:junit-jupiter-engine:5.10.0",
        "org.junit.jupiter:junit-jupiter-params:5.10.0",
        "org.junit.platform:junit-platform-console:1.10.0",
        "io.kotest:kotest-assertions-api-jvm:5.7.2",
        "io.kotest:kotest-assertions-core-jvm:5.7.2",
        "io.kotest:kotest-assertions-shared-jvm:5.7.2",
        "io.kotest:kotest-common-jvm:5.7.2",
    ],
    fetch_sources = True,
    repositories = [
        "https://maven.google.com",
        "https://repo.maven.apache.org/maven2",
    ],
)

use_repo(
    maven,
    "maven",
)
```

**Comment by agluszak** [comment]
When I added git override to commit `687dc3578c1b315e8484a095ff6d4a83e696b21d` the error was gone, but another one is thrown now:

```
ERROR: An error occurred during the fetch of repository 'rules_jvm_external~override~maven~maven':
   Traceback (most recent call last):
        File "/home/andrzej/.cache/bazel/_bazel_andrzej/77e3eaab94558fc713e3f88014595919/external/rules_jvm_external~override/coursier.bzl", line 446, column 82, in _pinned_coursier_fetch_impl
                computed_artifacts_hash, old_hashes = compute_dependency_inputs_signature(
        File "/home/andrzej/.cache/bazel/_bazel_andrzej/77e3eaab94558fc713e3f88014595919/external/rules_jvm_external~override/coursier.bzl", line 309, column 57, in compute_dependency_inputs_signature
                excluded_artifact_inputs.append(_stable_artifact(artifacts))
        File "/home/andrzej/.cache/bazel/_bazel_andrzej/77e3eaab94558fc713e3f88014595919/external/rules_jvm_external~override/coursier.bzl", line 287, column 25, in _stable_artifact
                parsed = json.decode(artifact)
Error in decode: at offset 0, unexpected character "c"
ERROR: <builtin>: fetching pinned_coursier_fetch rule //:rules_jvm_external~override~maven~maven: Traceback (most recent call last):
        File "/home/andrzej/.cache/bazel/_bazel_andrzej/77e3eaab94558fc713e3f88014595919/external/rules_jvm_external~override/coursier.bzl", line 446, column 82, in _pinned_coursier_fetch_impl
                computed_artifacts_hash, old_hashes = compute_dependency_inputs_signature(
        File "/home/andrzej/.cache/bazel/_bazel_andrzej/77e3eaab94558fc713e3f88014595919/external/rules_jvm_external~override/coursier.bzl", line 309, column 57, in compute_dependency_inputs_signature
                excluded_artifact_inputs.append(_stable_artifact(artifacts))
        File "/home/andrzej/.cache/bazel/_bazel_andrzej/77e3eaab94558fc713e3f88014595919/external/rules_jvm_external~override/coursier.bzl", line 287, column 25, in _stable_artifact
                parsed = json.decode(artifact)
Error in decode: at offset 0, unexpected character "c"
ERROR: /home/andrzej/code/bazel/bazel-bsp/server/src/main/kotlin/org/jetbrains/bsp/bazel/server/BUILD:3:15: //server/src/main/kotlin/org/jetbrains/bsp/bazel/server:server depends on @rules_jvm_external~override~maven~maven//:ch_epfl_scala_bsp4j_2_13 in repository @rules_jvm_external~override~maven~maven which failed to fetch. no such package '@rules_jvm_external~override~maven~maven//': at offset 0, unexpected character "c"
ERROR: /home/andrzej/code/bazel/bazel-bsp/server/src/main/kotlin/org/jetbrains/bsp/bazel/server/BUILD:3:15: //server/src/main/kotlin/org/jetbrains/bsp/bazel/server:server depends on @rules_jvm_external~override~maven~maven//:org_eclipse_lsp4j_org_eclipse_lsp4j_jsonrpc in repository @rules_jvm_external~override~maven~maven which failed to fetch. no such package '@rules_jvm_external~override~maven~maven//': at offset 0, unexpected character "c"

```
